### ISSUE TITLE
Nullable in SQL Server

### ISSUE THREAD

**Issue by ryabikin** [fluentmigrator/fluentmigrator#1013]
Is there a way to suppress generating "NOT NULL" option when altering a column without Nullable() in SQL Server? 
I'm writing 
            Alter.Table("TABLE1").AlterColumn("COLUMN1").AsDecimal(38, 0)
and getting
           ALTER TABLE [dbo].[TABLE1] ALTER COLUMN [COLUMN1] DECIMAL(38,0) NOT NULL
I want to preserve current column nullability. It works as needed in Oracle. I'm trying to have common code for Oracle and SQL Server and getting a trouble with Nullable().

**Comment by fubar-coder** [comment]
It's not supported yet. I'll take a look and if it's easy enough (and most likely a non-breaking change) then it'll be released with 3.2.0.

**Comment by ryabikin** [comment]
Thanks!

**Comment by ikudjoi** [comment]
I think that's rather untrivial, because afaik there's no way to alter SQL Server column type without specifying nullability. So you'd need to first query the nullability first and use it when generating the alter statement.

`drop table if exists #foo;
create table #foo (Bar nvarchar not null);
select name, is_nullable From  Tempdb.Sys.Columns Where Object_ID = Object_ID('tempdb..#foo');
alter table #foo alter column Bar int;
select name, is_nullable From  Tempdb.Sys.Columns Where Object_ID = Object_ID('tempdb..#foo');`

In the example above first temp table with non-nullable column is created. Then it's altered to other datatype without specifying nullability. But that implicitly means nullable data type, which I could concur with the query.

**Comment by ryabikin** [comment]
Yes, you are right.
ALTER TABLE [dbo].[TABLE1] ALTER COLUMN [COLUMN1] DECIMAL(38,0) results in the same as
ALTER TABLE [dbo].[TABLE1] ALTER COLUMN [COLUMN1] DECIMAL(38,0) NULL
Nullability is not  preserved when NULL or NOT NULL is omitted. NULL is forced in  SQL Server

**Comment by fubar-coder** [comment]
OK, so it's just not possible on SQL Server without an additional round-trip to the database.  I'll close this issue until we have our own schema store (like Entity Framework Core).
