### ISSUE TITLE
Move to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1023]
Now that the [preview of Microsoft.Data.SqlClient is available in NuGet](https://www.nuget.org/packages/Microsoft.Data.SqlClient/), we should be able to use it.

**Comment by YeskaNova** [comment]
Microsoft.Data.SqlClient is no more in preview, I think it's a fair move to go for it.

**Comment by jzabroski** [comment]
It's coming.  Unfortunately, during COVID lockdown, I spilled tea on my keyboard, and am waiting on Amazon for a replacement, so I didn't get around to wrapping up 3.3.0 release this weekend.

**Comment by sturled** [comment]
Got a new keyboard? Any plans on wrapping this one up?

**Comment by chrisvfabio** [comment]
Any update on this?

**Comment by jzabroski** [comment]
https://github.com/dotnet/SqlClient#supportability

Just verified that this package works on 4.6.1

Merging.

**Comment by YanerTavuz** [comment]
It works but there seems to be some kind of locking of the dll for Microsoft.Data.SqlClient.SNI.
Example. I have an ASP.NET MVC 5 site which also runs migrations using FluentMigrator, hosting it in IIS and rebuilding the solution fails because the dll is locked by the IIS process. 
`using (var scope = ServiceProvider.CreateScope())` doesn't seem to help with releasing resources.
