### ISSUE TITLE
Is it possible to use DDL without migrations?

### ISSUE THREAD

**Issue by arudoy** [fluentmigrator/fluentmigrator#1029]
I want have possibility to use DDL operations without migrations.
I.e. I would like to execute the following code outside of UpdateDatabase.
```
Create.Table("Log")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("Text").AsString();
```
Is that possible?

**Comment by fubar-coder** [comment]
There are several possibilities:

- Maintenance migrations
  - Similar to normal migrations
  - Annotated with a `MaintenanceAttribute` instead of a `MigrationAttribute`
  - Always executed at the given migration stage, so you'd have to check if the table exists before you try to create one
- Profiles
  - Similar to normal migrations
  - Annotated with a `ProfileAttribute` instead of a `MigrationAttribute`
  - Always executed between the `BeforeProfiles` and `AfterAll` migration stages

**Comment by jzabroski** [comment]
Just wanted be curious. What is your use case?

**Comment by arudoy** [comment]
I need library for defining table structure in runtime.
We have GUI where user can create table, define it's columns, link that table to another etc - almost all DDL operations.
So, on server side I should write code which composes SQL non-queries like "CREATE TABLE" - and I'd like to use an already existing library for that.
Unfortunately, I can't find one.

**Comment by jzabroski** [comment]
Tagged this issue and #1085  with area-CodeGeneratorFriendliness as it seems like there are end users who would really find FluentMigrator more powerful if it had an internal API they could target (similar to LLVM) instead of the fluent syntax.

**Comment by jzabroski** [comment]
@arudoy Just revisiting this.  You can PROBABLY hack FluentMigrator to do what you want, today.  Simply create a custom logger with a log sink that is an object in your domain model where you want to output the script to.
