### ISSUE TITLE
Apply migration to every database in a shard using Elastic Database?

### ISSUE THREAD

**Issue by eparizzi** [fluentmigrator/fluentmigrator#1035]
I have a project which uses the [Elastic Database client library](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-database-client-library) to work with a multi-tenant application. Each database belongs to a single tenant.

I would like to use FluentMigrator to manage the schema of every database in the shard.

Ideally, I'd like to configure a runner with multiple connection strings (which I get from the Elastic Database client).

```csharp
    private static IServiceProvider CreateServices()
        {
            return new ServiceCollection()
                // Add common FluentMigrator services
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    // Add SQLite support to FluentMigrator
                    .AddSQLite()
                    // Set the connection string
                    .WithGlobalConnectionString("Data Source=test.db") // add multiple?
                    // Define the assembly containing the migrations
                    .ScanIn(typeof(AddLogTable).Assembly).For.Migrations())
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                // Build the service provider
                .BuildServiceProvider(false);
        }
```

Is there a supported way to do this? Or do I need to explicitly create and execute one runner per database?

**Comment by fubar-coder** [comment]
You have two options:

1. Create services per-database
2. Provide your own `IConnectionStringAccessor` implementation and run the migrator multiple times where your `IConnectionStringAccessor` implementation returns a different connection string on each run (static variable?)

**Comment by marcelogustavoreis** [comment]
> You have two options:
> 
> 1. Create services per-database
> 2. Provide your own `IConnectionStringAccessor` implementation and run the migrator multiple times where your `IConnectionStringAccessor` implementation returns a different connection string on each run (static variable?)

how can i do number 2?

**Comment by jzabroski** [comment]
@marcelogustavoreis That's just hooking into the .NET Core Microsoft DI.

**Comment by jzabroski** [comment]
@marcelogustavoreis You would have to use the In Process Runner way of executing migrations to change this, in case that is not obvious and you're new to .NET Core.  The In Process Runner gives you maximum control to override everything in FLuentMigrator.

**Comment by marcelogustavoreis** [comment]
> @marcelogustavoreis You would have to use the In Process Runner way of executing migrations to change this, in case that is not obvious and you're new to .NET Core. The In Process Runner gives you maximum control to override everything in FLuentMigrator.

i've a multi-tenant database, where each tenant has your own schema.
now, i'm trying to figure out how can i execute the runner for each schema in my database.

**Comment by jzabroski** [comment]
There is no sub-schema support built-in.  Just use conventions and have one migrations assembly for each schema.  If concern of one team accidentally running migrations in another teams' schema exists, set up unique Group MSA accounts to run the migrations, each with schema admin rights (assuming your database supports this, which if it supports schemas, it should).   What DB are you using btw?

**Comment by marcelogustavoreis** [comment]
> There is no sub-schema support built-in. Just use conventions and have one migrations assembly for each schema. If concern of one team accidentally running migrations in another teams' schema exists, set up unique Group MSA accounts to run the migrations, each with schema admin rights (assuming your database supports this, which if it supports schemas, it should). What DB are you using btw?

Mysql.
one assembly for each schema is not a good ideia for me, because i have a bunch of schemas and the table in it are the same. when i need to update some table, i must update all schemas. i'm looking for a good solution to do this.
there is any way to change the connectionstring before execute the runner?

**Comment by jzabroski** [comment]
Got it.
Don't do number two.  Do number one.  Create services per database.  You can hoist the In Process Runner services creation logic into a helper extension method that passes in a connection string.

**Comment by pergardebrink** [comment]
> Got it.
> Don't do number two. Do number one. Create services per database. You can hoist the In Process Runner services creation logic into a helper extension method that passes in a connection string.

Is there a specific reason to do option two? I hooked up number two, where I create a new DI scope per database with serviceProvider.CreateScope() and changed the connectionstring 

I have about 120 databases that needs to have the same set of migrations applied in one go and I could of course go with option one as you say and iterate over all of them...

**Comment by pergardebrink** [comment]
I should add that I didn't use the ConnectionAccessor, don't remember exactly now what stopped me from doing that, but I think I couldn't get it to behave exactly as I wanted in the scope, so I created this extensions method where I have deferred it like this to get different connectionstrings per scope:

```
public static IMigrationRunnerBuilder WithCustomConnectionString(this IMigrationRunnerBuilder builder, Func<IServiceProvider, string> configureConnectionString) 
{
            builder.Services.AddScoped((Func<IServiceProvider, IConfigureOptions<ProcessorOptions>>)((IServiceProvider s) => new ConfigureNamedOptions<ProcessorOptions>(Options.DefaultName, delegate (ProcessorOptions opt) {
                opt.ConnectionString = configureConnectionString(s);
            })));
            return builder;
}
```

**Comment by jzabroski** [comment]
> Is there a specific reason not to do option two?

He had the same "database" but different schemas. He needs to inject just the assembly. Plus, by doing it this way you can use the same connection string. In his case, it was clear the only real variation in the connection string was the tenant (database schema). Since he is using MySQL, schemas map to actual databases. Other engines like SQL Server allow multiple schemas per DB.

By creating separate services, and only passing in the assembly, you also avoid bugs where, if you do want a unique admin user per db, you guarantee all Migrations can run against that DB. This paragraph and point is really MySql specific. 

I'm not clear if you have the same requirements.

**Comment by c17r** [comment]
I'm in a similar boat of multi-tenant with no data commingling, my layout is
1. shared_db: user accounts, site configuration, includes mapping a client to an ops database
1. ops_###_db: operational data, one per client
1. reporting_db: data warehouse

I'm using Tags to map a migration to a database "type". My migration plan is to:
1. run the shared migrations
1. query the client<->ops mapping table in shared to get all the ops that need upgrading
1. loop through all the ops running their migrations
1. run the reporting migrations

Becomes more difficult if we have to split the ops databases to multiple servers but I'll burn that bridge when I get there 😆 

If I'm understanding correctly, I'll need to setup/teardown the service collection for each of my types since currently there is only `WithGlobalConnectionString` which stores in a singleton.

**Comment by jzabroski** [comment]
@c17r Thanks for the detailed use case layout.  Very helpful.

WithGlobalConnectionString is per service provider.  So, if you're _only_ referencing FluentMigrator objects within your DI scope, you can just create multiple service providers and dispose of them when you're done.  The "Global" is really per ServiceCollection _at the point you call `BuildServiceProvider();`_
