### ISSUE TITLE
MigrationStage.AfterAll doesn't get executed when registering migrations via .ScanIn(typeof(Program).Assembly).For.Migrations()

### ISSUE THREAD

**Issue by kalar-dk-fitnessworld-com** [fluentmigrator/fluentmigrator#1062]
When trying to run a Maintainance script on sql server it doesn't get executed. I've tried to step into the source and it seems like AssemblySourceOptions doesn't return any assemblies. My entire source is here. I use .net core. What is the problem. I cannot find documentation on this.

My goal is to have all stored proc applied on the database on every single Migrate run - via the class Id_999999999999_RunAllStoredProcedures. 
```
class Program
    {
        static void Main(string[] args)
        {
            IServiceCollection services = new ServiceCollection();
            const string connectionString = @"Server=.\SQLEXPRESS;Database=Cv;Trusted_Connection=true";
            services
                .AddFluentMigratorCore()
                .ConfigureRunner(
                    x => x.AddSqlServer2016()
                        .WithGlobalConnectionString(connectionString)
                        .ScanIn(typeof(Program).Assembly).For.Migrations());
            var provider = services.BuildServiceProvider();

            using (IServiceScope scope = provider.CreateScope())
            {
                IMigrationRunner runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                runner.MigrateUp();
            }
        }
    }

    [Migration(1)]
    public class TestMigration : Migration
    {
        /// <inheritdoc />
        public override void Up()
        {
            Create.Table("test").WithColumn("Id").AsString();
        }

        /// <inheritdoc />
        public override void Down()
        {
            throw new NotImplementedException();
        }
    }

    [Maintenance(MigrationStage.AfterAll)]
    public class Id_999999999999_RunAllStoredProcedures : Migration
    {
        public override void Up()
        {
            Execute.Sql("CREATE OR ALTER PROC a AS BEGIN SELECT 1 END");
        }

        public override void Down()
        {
            //NOOP
        }
    }
```

**Comment by jzabroski** [comment]
Hi @kalar-dk-fitnessworld-com , I've been trying to get to this.  If I could give one piece of advise, it's to upload a full Visual Studio sln to GitHub so I can clone it and instantly debug it for you.  This is a great repro, but supporting as many user issues as we do, every second the user saves reporting an issue is time we can put into investigating vs. doing the work of trying to put together a solution.

On the surface, what you're describing doesn't make sense - I can see you're calling things correctly, so it must be something subtle that requires actual debugging vs. just eyeball test.\

As one suggestion, did you try enabling logging to the console:

`.AddLogging(lb => lb.AddDebug().AddFluentMigratorConsole())`

See here for instruction on logging: https://github.com/fluentmigrator/fluentmigrator/blob/master/samples/FluentMigrator.Example.Migrator/Program.DependencyInjection.cs#L32

**Comment by kasperbirkelund** [comment]
Thanks - this is me again from an other account. I have uploaded a stripped down repo solution here: https://github.com/kasperbirkelund/FluentMigratorRepro

(you just need to change connectionstring)

**Comment by jzabroski** [comment]
Thanks.  Taking a quick look now.

**Comment by jzabroski** [comment]
I can reproduce your issue, but I'm not yet sure why it's happening.  On the surface, it looks like a bug.

Things I tried:
1. Create a blank Cv database every time.
2. Don't create a blank Cv database every time.  Have the VersionInfo table populated with migration id 201909231355 to see if you are running into some variant of https://github.com/fluentmigrator/fluentmigrator/issues/1017 - This doesn't appear to be the case.
3. Seeing if the NON-presence of Profiles affects / short-circuits AfterAll maintenance migrations. 
4. Put breakpoint on `runner.MigrateUp();` and see if runner.CaughtExceptions in the Quick Watch > 0.  Not the case.

Things still to try (you're welcome to try yourself):
1. Does it work with FluentMigrator Console
2. Does it work with dotnet-fm global tool
3. Add your sample project to the master branch solution, step through [https://github.com/fluentmigrator/fluentmigrator/blob/2b73a170931b6fda68586b4a3d3f83b5f34ce07f/src/FluentMigrator.Runner.Core/Infrastructure/DefaultMigrationConventions.cs#L56](GetMaintenanceStageImpl)

Have to jump back to work.

Some quick self-notes for me to follow-up on:
- [ ] Is the demo app in master build-able from source?
- [ ] Should we change the demo app logging line to say: `lb.SetMinimumLevel(LogLevel.Information)` instead of `.AddDebug()` - this call is in `Microsoft.Extensions.Logging`
- [ ] When we moved from FluentMigrator 1.8 to 2.x, we removed the Announcer interface, which removed some of the helpful tracing utilities.

**Comment by kasperbirkelund** [comment]
Thanks for your reply. 

To me it looks like the RunnerContext.Targets is not set as expected while executing from code (maybe that is different while running from cmd)

**Comment by jzabroski** [comment]
No, RunnerContext is `[Obsolete]` for a reason.

I think this is your problem, you are welcome to try to fix it yourself and submit a PR if my hunch is right:

https://github.com/fluentmigrator/fluentmigrator/blob/3aedfcb0858388d96366c42312abe8eac67211c3/src/FluentMigrator.Runner/MaintenanceLoader.cs#L48

**Comment by jzabroski** [comment]
@kasperbirkelund  OK, I found the problem.  This is related to #886 except instead of Profiles, Maintenance migrations.  I'm pushing to my fork of your repo a working workaround, but I have not yet minimized it to the minimal solution required.

**Comment by jzabroski** [comment]
https://github.com/jzabroski/FluentMigratorRepro

**Comment by jzabroski** [comment]
@kasperbirkelund @kalar-dk-fitnessworld-com  I have updated my fork of your repro with the minimal solution, and confirmed that you only need the AddSingleton call.  Please ignore my comments about the bug being in MaintenanceLoader.

This is 100% an edge case as part of #886.  

@fubar-coder I think we can permanently fix this a couple of ways.  The instinctive way for me is to create a marker interface IFluentMigratorAttribute and change MaintenanceAttribute, ProfileAttribute and MigrationAttribute to implement the marker interface.  We can then use reflection to query classes implementing that marker interface.

**Comment by kalar-dk-fitnessworld-com** [comment]
Thanks it works :-)

**Comment by fubar-coder** [comment]
@jzabroski I'm not sure if having a marker interface is overengineering or required to simplify the implementation....

**Comment by jzabroski** [comment]
@fubar-coder  I'm sure you trust me , but... How would you simplify the implementation?

**Comment by TonySullivan** [comment]
Have you guys made any progress on this? I am having the same issue.

**Comment by jzabroski** [comment]
@TonySullivan  There is a workaround, here: https://github.com/fluentmigrator/fluentmigrator/issues/1062#issuecomment-534163590

There is no immediate thing needing "progress".  If you'd like to submit a PR to make things smoother for users, we're happy to take them.  That said, this issue should not have been closed.

**Comment by lszczygielek** [comment]
Hi, I would like to add that issue still exists. I start today work with FluentMigrator and I spent 3 hours to find this ticket, which has a workaround. It would be good to update documentation how to write In-Process application with working `MaintenaceAttribute`.
https://fluentmigrator.github.io/articles/migration-example.html
https://fluentmigrator.github.io/articles/glossary.html

In summary: workaround which adds `IAssemblySourceItem` (I don't know what it is, I just start play with FluentMigrator) which suggests @jzabroski works.

**I also found another workaround without adding `IAssemblySourceItem`:**
Changing `.ScanIn(typeof(Program).Assembly).For.Migrations()`
to `.ScanIn(typeof(Program).Assembly).For.All()` also works.

I tried also combination, but this doesn't work.
```
.ScanIn(typeof(Program).Assembly)
    .For.Migrations()
    .For.EmbeddedResources()
    .For.VersionTableMetaData()
```

**Comment by jzabroski** [comment]
@lszczygielek Makes sense to me.  For the In-Process Runner, see #1208 for thoughts on how we might improve the experience for people trying to customize FluentMigrator (so that the "happy path" just works and users opt-in automatically to fixes as they upgrade a "happy path" nuget dependency).  The big drawback right now with In-Process Runners is:

1. Current In-Process Runners effectively fork the logic in `FluentMigrator.DotNet.Cli` .NET Core CLI Tool.
2. They're really only needed for a couple of reasons:
    1. Fine-grained control over ServiceCollection DependencyInjection
    2. #1016 - out-of-process runners don't "know" your deps.json file and can't compute the transitive closure of all your dependencies for your default AssemblyLoadContext - which leads us to the next reason:
    3. People who want to host FluentMigrator in ASP.NET Core applications but can't because the existing service collection extensions that ship in-box with FluentMigrator calls `BuildServiceProvider()`
    4. We (or I) did not know about [`TryAddSingleton`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.tryaddsingleton?view=dotnet-plat-ext-3.1)
    5. Fine-grained control over logging, e.g. use Serilog and hook into DataDog logging target
    6. Working around a bug/limitation

In other words, rather than improve documentation for building in-process runners, it might make sense to spend more effort on #1208 so that the documentation is just there when you're using IntelliSense and clicking _Go To Implementation_ in VisualStudio/Resharper.  Does that make sense?  I'm all for accepting a PR to https://github.com/fluentmigrator/documentation to help with this, too, but the initial design was to target making everything-injectable/everything-possible, which it mostly does (`ITypeMap` is not injectable in 3.0 branch - I think it is in 4.0 develop branch but can't remember).

> I tried also combination, but this doesn't work.
> 
> ```
> .ScanIn(typeof(Program).Assembly)
>     .For.Migrations()
>     .For.EmbeddedResources()
>     .For.VersionTableMetaData()
> ```

I think the reason this doesn't work is there is no test coverage for it, as far as I can see.  Baby step one is probably to do a code spike and cover this area with assertions.

**Comment by jzabroski** [comment]
Possible duplicate #1607

**Comment by jzabroski** [comment]
I added a comment and updated the sample to help avoid this booby trap until we have time to do a proper fix. https://github.com/fluentmigrator/fluentmigrator/commit/d0c4c362138bd4bb60cdc0d317236bcf2d54ded5
