### ISSUE TITLE
Call migrate down for a specific migration using command line

### ISSUE THREAD

**Issue by gandarez** [fluentmigrator/fluentmigrator#1120]
Is there a way to call migrate down for a specific migration (let's say for a Profile) via command line?

I can easily migrate down a specific migration.
```c#
migrationRunner.Down(new SomeMigration());
```

**Comment by fubar-coder** [comment]
No, you can only specify the migration version.

**Comment by jzabroski** [comment]
@gandarez You could write an extension method to read the Version metadata on all migrations, and pick the one that matches your constant.  Since C# allows constant value expressions in attributes, you can also therefore extract out this magic # migration and put it in a special static class that your In-Process Runner uses.  You then call your standard in-process runner with a range between the magic #, which will force it to run only one migration.

It's rather non-standard, and pretty obfuscated, if you ask me.  Just explaining how I would think to approach the problem.
