### ISSUE TITLE
FluentMigrator.VStudio - Simple nuget package for integration with VisualStudio

### ISSUE THREAD

**Issue by crimcol** [fluentmigrator/fluentmigrator#1134]
I've created a simple nuget package with commands for integration with VisualStudio. The source code is here: https://github.com/crimcol/FluentMigrator.VStudio 

For now it supports following commands:

```
Add-FluentMigration
Update-FluentDatabase
Rollback-FluentDatabase
```

The package name is: FluentMigrator.VStudio.1.0.0.nupkg 

I receive following error message when try to publish:

> (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.)

Probably it is because FluentMigrator ID is reserved and I need some permissions. 
It would be nice if you can allow me to publish this package.

**Comment by jzabroski** [comment]
@crimcol Generally, the reason prefixes are reserved is so that the organization maintains all those packages as a single "ring of trust".  It is a brand name, which has trustworthy characteristics among library "shoppers".

That said, your github project has none of the three functions posted, so I think as it is currently represented at HEAD of your master branch, there is zero chance we'd publish this for you, since we can't see all the code and what it does.  Am I missing something?

**Comment by jzabroski** [comment]
@crimcol Wait!  I am so sorry - I see the code is here: https://github.com/crimcol/FluentMigrator.VStudio/blob/master/src/FluentMigrator.VStudio.psm1

As some feedback, I think this is probably the wrong way to support this - the right way is to write a PowerShell binary cmdlet via C# where you can tightly integrate with our C# API.  I'll try to elaborate with some more feedback, if you're interested.   I gave a talk this past year on how to write PS Binary cmdlets in PowerShell Core using the PowerShell SDK.

**Comment by crimcol** [comment]
@jzabroski thank you for feedback.
But I do not understand why it should be implemented as PS Binary?
In my understanding PS Binary it is just another way of implementation.

This solution already have all necessary things to be build as nuget package and you can try yourself by running build.cmd file.

Your Readme file pointing to this package as a third-part nuget package:
https://github.com/ritterim/fluentmigrator-generator
It has same structure as mine solution.

**Comment by jzabroski** [comment]
I did not realize (in a bump on the head sort of way) that there were other packages using the FluentMigrator prefix. It looks like people have forked ritterim's work rather than contributing back, which sort of sucks for ritterim (less credit).

In terms of other feedback, my main need when using FluentMigrator is a way to "archive migrations".  Typically, this means with the new C# SDK style project format that we glob all files in an Archive folder as not included in the project for building, but its still searchable from Visual Studio if you select "Show all files" and use "Search External Items".  Handy if you want to clean up your migrations folder but dont want to hard delete old migrations, as they're effectively example code for new team members and the trickier migrations are at your finger tips even after they're archived.

**Comment by crimcol** [comment]
@jzabroski thank you for feedback.
Not sure what do you mean under "new SDK style project".
If migrations not included in the project they will not build and will not be applyed in result.

Anyway, how does it related to the publishing a package?

**Comment by crimcol** [comment]
This is a reply from @fubar-coder in email:

> Hi,
>
>thank you for your contribution to the FluentMigrator ecosystem. The name reservation was intentional, because every user of FluentMigrator.* packages should be safe and confident that the packages are from the FluentMigrator project.
>We're having the following options here:
>
> - I upload the package and add you as owner, which should give you the right to update the packages
> - You put the project under the hood of the FluentMigrator project, and I add you as administrator for this project and NuGet namespace
>Please open an issue on GitHub. I'll discuss this matter with the co-maintainer.
>
>Kind regards,
>
>Mark Junker

Hope it helps.

**Comment by fubar-coder** [comment]
The name reservation was done **after** other package authors submitted their packages on nuget.org. The reservation prevents this for all new packages.

**Comment by crimcol** [comment]
Does that mean I should use another package name?

Thanks.

**Comment by jzabroski** [comment]
For now, yes. I think running an open source project is hard, mainly due to
the sheer volume of questions people ask on how to do x with
FluentMigrator. Reserving the prefix helps prevent people from getting
confused as to where to file bugs.

On some level it might make sense to have some official FM Visual Studio
package manager console version, but I've always anticipated the console
would eventually fade away and MS would stop supporting it.

I personally don't have appetite to support Powershell. I find I am ten to
a hundred times more productive in c#.

**Comment by jzabroski** [comment]
@crimcol Closing.  Feel free to submit a PR to update the README with a link back to your project.  I have no issue helping you promote the tool you worked hard on.
