### ISSUE TITLE
versionInfo.appliedOn set to UTC time

### ISSUE THREAD

**Issue by lishen5953** [fluentmigrator/fluentmigrator#1143]
The value in VersionInfo table, appliedOn field is set to UTC time.  Is there a way to have it set to local time?

**Comment by jzabroski** [comment]
Create a view in your database that wraps version info and translates it to local time.

Do NOT store datetime in anything except UTC time.  The reason is simple.  You can end up with ambiguous DateTime values that have either two valid UTC timepoints or no valid UTC timepoints.

Consider also a DevOps team that sets-up multi-region cloud failover strategy to failover to west coast but your standard is in east coast.  You then do a deployment on west coast to fix the runaway problem that caused east coast to go down in the first place.

Abstracting your IT infrastructure also means abstracting the location of your servers, ENTIRELY.

If you're doing DevOps, you want to use UTC time.

If you are using SQL Server 2017 or later, you can use the [`AT TIME ZONE`](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15) conversion helpers on DateTime, DateTime2 and DateTimeOffset to translate UTC to local time.

**Comment by lishen5953** [comment]
John,
Appreciate your response.
Li
    On Tuesday, January 7, 2020, 09:56:39 AM PST, John Zabroski <notifications@github.com> wrote:  
 
 
Create a view in your database that wraps version info and translates it to local time.

Do NOT store datetime in anything except UTC time. The reason is simple. You can end up with ambiguous DateTime values that have either two valid UTC timepoints or no valid UTC timepoints.

Consider also a DevOps team that sets-up multi-region cloud failover strategy to failover to west coast but your standard is in east coast. You then do a deployment on west coast to fix the runaway problem that caused east coast to go down in the first place.

Abstracting your IT infrastructure also means abstracting the location of your servers, ENTIRELY.

If you're doing DevOps, you want to use UTC time.

If you are using SQL Server 2017 or later, you can use the AT TIME ZONE conversion helpers on DateTime, DateTime2 and DateTimeOffset to translate UTC to local time.
