### ISSUE TITLE
Only structure/data migrations up or down

### ISSUE THREAD

**Issue by Odonno** [fluentmigrator/fluentmigrator#1145]
With SQL databases, you have two kind of operations: some on the structure (CREATE TABLE) and others on the data (INSERT INTO, UPDATE SET).

Based on this, there are sometimes need to only apply migrations for data (and not structure). I know there is a system of tags in FluentMigrator but that imply to be extremely good to separate all migrations in two (if necessary).

What I would suggest is to be able to use another option `SkipStructureMigration` on `MigrateUp` and `MigrateDown` methods. If enabled, it will only trigger operations that update the data and nothing else.

**Comment by jzabroski** [comment]
Hi David,

I'm trying to unpack your request, and make sure I understand it, since FluentMigrator does not have `MigrateUp` or `MigrateDown` methods - they're called `Up` and `Down`.  Assuming this was just a typo, here's my analysis of your request:

SQL supports DDL (Data Definition Language) and DML (Data Manipulation Language).

I personally use `TagsAttribute` to annotate which environments can use DML statements:

```c#
[Migration(1, "Update user names")]
[Tags(TagNames.Development, TagNames.Alpha, TagNames.Beta, TagNames.Production)]
public class UpdateUserNames : ForwardOnlyMigration {
  public void Up() {
    //etc...
  }
}
```
In my scenario, it doesn't make sense to run data migrations on the unit test database, since it contains no data and is either a no-op or in the case of inserts that depend on certain production IDs for lookup tables, will simply fail.  So, I deliberately omit `Tags.UnitTest` above so that my data migrations never run on a unit test database.

However, that doesn't explain why you would ever want to skip DDL migrations and only apply data migrations - I've literally never thought of that scenario, even though its the opposite of the one above.  Which makes me wonder - why not just use Tags?  Is there something special you want to do differently in Up and Down methods?  If so, why?

For example, Are you asking to have a way to annotate `Up()` and `Down()` methods?  For example, one way could be to allow Tags to be targeted on methods:

```c#
[Migration(1, "Update user names")]
public class UpdateUserNames : ForwardOnlyMigration {
  [Tags(TagNames.Development, TagNames.Alpha, TagNames.Beta, TagNames.Production)]
  public override void Up() {
    //etc...
  }
}
```

Alternatively, there could just be `SkipStructu

**NOTE: I am not saying we would allow this, just trying to make sure I understand your request at this point.**

Do I understand what you are asking for?

**Comment by Odonno** [comment]
Well, first, I was not targeting the Up/Down methods of a migration but the MigrateUp/Down of the migration runner.

There is a clear use case for unit testing when you want to replay the migrations to have a clean database on each test run. My suggestion was to optimize the process by simply erase data and only re-apply data migrations (since the structure is already there).

Another thing that bothers me is that we already have migrations with both structure and data updates... That's why the Tag feature is useless in that case. But if we were rigorous, we would use it like the way you described. That would totally makes sense.

To complete, I believe that when you pass down the `SkipStructureMigration` option to every migration step, it can clearly indicates if it is a structure update or a data update. And in that case, do it or not. It does not seem like a difficult but it will add a lot of conditions in the code.

Of course, I am open to other ideas.

**Comment by jzabroski** [comment]
So, I'm open to brainstorming.

But, if I read this comment correctly:

> Another thing that bothers me is that we already have migrations with both structure and data updates... That's why the Tag feature is useless in that case. But if we were rigorous, we would use it like the way you described. That would totally makes sense.

I recommend archiving migrations and creating a new "Baseline" database script called CreateSchema.sql that creates your schemas, tables, views, stored procedures, etc. after every release, ideally.

> My suggestion was to optimize the process by simply erase data and only re-apply data migrations (since the structure is already there).

I'm guessing this suggestion was with your teammates on your project.  I don't advice doing it this way.  Instead, use Maintenance migrations and a UnitTest Tag, and run the Maintenance using MaintenanceStage.AfterAll.  If you use dependency injection, you can inject your test data as an IEnumerable into this Maintenance Migration, so that your teammates aren't all editing the same file, and you can use Solution Explorer to see the tables that are "core lookup tables" in the system.  Basically, you want to think of your test data as either being core to the system functioning or not, and ideally keep that core test data as small as possible, because it actually makes your tests really brittle.  You might also want a separate set of lookup tables for your Sales team or for your Demo environment.  Those all can go in a MaintenanceStage.AfterAll with different Tags for the various environments.

The other advice I can give to speed up integration tests is to not generate large object graphs.  It literally adds no value.  But frameworks like Effort do this.

The last piece of advice?  Don't drop and re-create your database.  Just truncate all tables instead.  It's way faster.  If you really care about "prisitine database" for some reason like SaaS provisioning test, then use docker to spin up a brand new database but still follow the same process I outlined above.

In terms of brainstorming:
As for a cleaner way to structure all this, what I really want is a more flexible way to write Up/Down commands that isn't tied to classes.  The idea is that the current structure causes some modularity issues when you really need a transaction that's outside the current outer transaction scope.  For example, disabling fulltextsearch in SQL Server can't be run inside a transaction.  I was thinking of something like "monad transformers" based on how Haskell programmers interact with State IO by representing the State as a monad and having transformations applied to that State.  But, I haven't been motivated to implement it since I think its too fancy a concept for the .NET Community to absorb at the moment.  If I could think of a way to "hide monad transformers" from users so they don't realize that's what they're doing, then I would have done it by now.

**Comment by jzabroski** [comment]
@Odonno Hi David, just wondering if I am on the right track in terms of what you are asking for...

**Comment by Odonno** [comment]
@jzabroski Hi John. Sorry, never had time to experiment on this since your last comment. I really like your part on brainstorming. The monadic part seems interesting but I am not sure my request was that complex :)
We could have had something like an object called `Features` which can be close to a feature flag functionality where you can activate some parts of the library (insert, update, delete, etc...).

I know that's not the primary concerns of the library which is to execute migrations and it does it really well because I use it regularly.

Anyway, I will try to find time to do my experiments on this on my side and I may reach out to you in the future. Thank you for your deep explanation.

**Comment by ngvtien** [comment]
@jzabroski - to expand on this idea a bit further, I've come across a situation where I need to skip certain migration because certain database metadata doesn't exists at the time but these migration will run when those conditions are met.

There might be a few reasons as to why this is
- One codebase against multiple version of the database
- Certain application features requires different database metadata to be switch on/off at different time depend on customer needs
- Multiple teams working against the same database
- Different version of stored proc depends on what feature customer opt in

For example, if we can decorate with some kind of attribute and allow the condition context to be specified

`
[Migration(1234,` "Update user names")]
[Condition("SELECT 1 WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ='test' and TABLE_NAME='tableName' and COLUMN_NAME='columnName')")]
public class UpdateUserNames : Migration {
  public void Up() {
    // Only execute the migrate if the condition above met
    //etc...
  }

  public void Down() {
    //etc...
  }
}
`
Hope this make sense

**Comment by jzabroski** [comment]
@ngvtien This already exists.  Look at the examples folder.  Although, if I understand you correctly, you want a a SqlConstraint sub-class to MigrationConstraintAttribute.  

To be honest, I hate MigrationConstraintAttribute - it doesn't work 100% correctly, in that the VersionInfo metadata is only loaded at the start of the runner, not after every migration, so the behavior is in my opinion not intuitive. https://github.com/fluentmigrator/fluentmigrator/blob/master/samples/FluentMigrator.Example.Migrations/3_UpdateNotesByScript.cs

**Comment by jzabroski** [comment]
Please open a new issue Or Discussion to discuss further.  I am going to lock this as I dont like people commenting on old issues as I can sometimes miss comments and that is not my intention to ignore people
