### ISSUE TITLE
Registration fluentmigrator with Castle Windsor IoC container

### ISSUE THREAD

**Issue by slad08** [fluentmigrator/fluentmigrator#1166]
Hello.
I'm working on project Web API what use Castle Windsor IoC container.Can you help me, can i register  fluentmigrator with this container?I found sample with Microsoft.Extensions.DependencyInjection
https://fluentmigrator.github.io/articles/quickstart.html?tabs=runner-in-process

**Comment by jzabroski** [comment]
If you're using ASP.NET Core Web API, my recommendation is to not expose your IoC container but instead use Microsoft.Extensions.DependencyInjection.  The main reason for this is that MS DI enforces a certain "architectural style" for managing dependencies that prevents unmaintainable code.  Probably the one controversial area here is automating Factory Method and Service Locator patterns via generic versions of these patterns.  For that, containers like Grace and DryIoC are arguably better.

Furthermore, you really just need to look at the benchmarks to see how much overhead you're adding by using Castle Windsor: https://github.com/danielpalme/IocPerformance#basic-features - Grace and DryIoC are literally 20x to 124x faster.  When you consider that IoC is a core path through your system on every request, you should think deeply on whether you want to really use Windsor in a project. - I realize you may already be deep down this path in a project, and your coworkers may hate me for making such suggestions :), but there really is a lot of pragmatism associated with "dumbing things down". - _If there are specific design patterns in Windsor you use today that you feel you can't do in Microsoft DI vanilla, let's discuss those, too_ - years ago I moved from Ninject to DryIoC.  My current head of engineering prefers Autofac, which is "middle of the road quality" performance wise but has great docs and active maintainers, but simply because he's been using it for 10+ years and hasn't changed his stack in 10 years.

That said, it's not a bad idea to post one example of at least one DI container besides Microsoft DI.  There are past issues people have run into such as #1065 (open) and #1079 (closed with workaround provided - consider that workaround too).

**Comment by adri360** [comment]
Hi, 
I know that it's an old thread. But, I've been searching a lot, but I haven't found any concrete examples with Castle Windsor or any other DI library.
Is it compatible?

**Comment by adri360** [comment]
> Si usa ASP.NET Core Web API, mi recomendación es no exponer su contenedor IoC, sino usar Microsoft.Extensions.DependencyInjection. La razón principal de esto es que MS DI impone un cierto "estilo arquitectónico" para administrar las dependencias que evita el código que no se puede mantener. Probablemente, el área controvertida aquí es la automatización de patrones de Factory Method y Service Locator a través de versiones genéricas de estos patrones. Para eso, los contenedores como Grace y DryIoC son posiblemente mejores.
> 
> Además, realmente solo necesita mirar los puntos de referencia para ver cuántos gastos generales está agregando al usar Castle Windsor: https://github.com/danielpalme/IocPerformance#basic-features : Grace y DryIoC son literalmente 20x a 124x más rápidos . Cuando considera que IoC es una ruta central a través de su sistema en cada solicitud, debe pensar profundamente si realmente desea usar Windsor en un proyecto. - Me doy cuenta de que es posible que ya esté en lo más profundo de este camino en un proyecto, y sus compañeros de trabajo pueden odiarme por hacer tales sugerencias :), pero realmente hay mucho pragmatismo asociado con "simplificar las cosas". - _Si hay patrones de diseño específicos en Windsor que usa hoy que siente que no puede hacer en Microsoft DI vanilla, hablemos de eso también_- Hace años me mudé de Ninject a DryIoC. Mi actual jefe de ingeniería prefiere Autofac, que es de "calidad intermedia" en cuanto a rendimiento, pero tiene excelentes documentos y mantenedores activos, pero simplemente porque lo ha estado usando durante más de 10 años y no ha cambiado su pila en 10 años.
> 
> Dicho esto, no es una mala idea publicar un ejemplo de al menos un contenedor DI además de Microsoft DI. Hay problemas anteriores con los que la gente se ha topado, como [el n.º 1065](https://github.com/fluentmigrator/fluentmigrator/issues/1065) (abierto) y [el n.º 1079](https://github.com/fluentmigrator/fluentmigrator/issues/1079) (cerrado con solución alternativa provista; considere esa solución alternativa también).

Hola,
se que es un hilo viejo. Pero, he estado buscando mucho, pero no he encontrado ningún ejemplo concreto con Castle Windsor o cualquier otra biblioteca DI.
¿Es compatible?

**Comment by adri360** [comment]
Hello,
I know this is an old thread. But, I've been searching a lot, but I haven't found any concrete example with Castle Windsor or any other DI library.
Is it compatible?

**Comment by adri360** [comment]
> Si usa ASP.NET Core Web API, mi recomendación es no exponer su contenedor IoC, sino usar Microsoft.Extensions.DependencyInjection. La razón principal de esto es que MS DI impone un cierto "estilo arquitectónico" para administrar las dependencias que evita el código que no se puede mantener. Probablemente, el área controvertida aquí es la automatización de patrones de Factory Method y Service Locator a través de versiones genéricas de estos patrones. Para eso, los contenedores como Grace y DryIoC son posiblemente mejores.
> 
> Además, realmente solo necesita mirar los puntos de referencia para ver cuántos gastos generales está agregando al usar Castle Windsor: https://github.com/danielpalme/IocPerformance#basic-features : Grace y DryIoC son literalmente 20x a 124x más rápidos . Cuando considera que IoC es una ruta central a través de su sistema en cada solicitud, debe pensar profundamente si realmente desea usar Windsor en un proyecto. - Me doy cuenta de que es posible que ya esté en lo más profundo de este camino en un proyecto, y sus compañeros de trabajo pueden odiarme por hacer tales sugerencias :), pero realmente hay mucho pragmatismo asociado con "simplificar las cosas". - _Si hay patrones de diseño específicos en Windsor que usa hoy que siente que no puede hacer en Microsoft DI vanilla, hablemos de eso también_- Hace años me mudé de Ninject a DryIoC. Mi actual jefe de ingeniería prefiere Autofac, que es de "calidad intermedia" en cuanto a rendimiento, pero tiene excelentes documentos y mantenedores activos, pero simplemente porque lo ha estado usando durante más de 10 años y no ha cambiado su pila en 10 años.
> 
> Dicho esto, no es una mala idea publicar un ejemplo de al menos un contenedor DI además de Microsoft DI. Hay problemas anteriores con los que la gente se ha topado, como [el n.º 1065](https://github.com/fluentmigrator/fluentmigrator/issues/1065) (abierto) y [el n.º 1079](https://github.com/fluentmigrator/fluentmigrator/issues/1079) (cerrado con solución alternativa provista; considere esa solución alternativa también).

Hi,
I know this is an old thread. But, I've been searching a lot, but I haven't found any concrete example with Castle Windsor or any other DI library.
Is it compatible?

**Comment by jon49** [comment]
Is there much reason to even have dependency injection with this library? I don't plan to unit test any of it and that is normally the main reason I use dependency injection. I'm not sure what dependency injection really buys us for this library.

**Comment by jzabroski** [comment]
Yes, dependency injection allows people to add object contexts to their migrations, as well as override default configurations. In addition, if using Execute.WithConnection, allows joining database contexts like an ORM database context to the existing FM connection, thereby ensuring transaction integrity.
