### ISSUE TITLE
MigrationRunnerBuilderExtensions.ScanIn could have support for generic assemblies

### ISSUE THREAD

**Issue by danielamorais** [fluentmigrator/fluentmigrator#1189]
I've the following code and I want to add a generic type of an assembly to my scanIn call. I've tried to create a generic Migration Class (such as _MyBaseClass : Migration_ so my assemblies could inherit from it and the framework detects it automatically) 
```
private static IServiceProvider CreateServices()
        {
            return new ServiceCollection()
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    .AddPostgres()
                    .WithGlobalConnectionString(
                        "Server=127.0.0.1;Port=5432;Database=pdv;User Id=postgres;Password=postgres;")
                    // Define the assembly containing the migrations
                    // AddProduct.Class
                    .ScanIn(typeof(MyBaseClass).Assembly).For.Migrations())
                .AddLogging(lb => lb.AddFluentMigratorConsole().SetMinimumLevel(LogLevel.Debug))
                .BuildServiceProvider(false);
        }
```

My Class
```
    public class AddProductData : MyBaseClass 
    {
        public override void Up()
        {
            Create.Table("product")
                .WithColumn("id").AsInt64().PrimaryKey().Identity()
                .WithColumn("name").AsString()
                .WithColumn("sku").AsString()
                .WithColumn("barcode").AsString()
                .WithColumn("price").AsDecimal()
                .WithColumn("cost").AsDecimal();

            Insert.IntoTable("product")
                .Row(new { name = "Cerveja Amstel", sku = "ABCDEF", barcode = "6009801472034", price = 2.39M, cost = 2.20M });
        }

        public override void Down()
        {
            //Do nothing
        }
    }
```

MyBaseClass
```
    [Migration(1)]
    public class MyBaseClass: Migration
    {
        public override void Up()
        {
            //Do nothing
        }

        public override void Down()
        {
            //Do nothing
        }
    }
```

How can I do this? I don't want to write duplicate code or to call scanIn for every class I create.

**Comment by jzabroski** [comment]
Hi Daniela,
I'm heading to bed but try searching for open generic factory pattern in c#. ScanIn I believe just creates a simple factory using a closed type. I think this is the right set of clues. Or so I hope.

**Comment by jzabroski** [comment]
@danielamorais There are a couple of things here:

1. It's not a _generic_ migration class - it's a _base_ migration class.  I misread your post last night, sorry.
2. You can't put the `[Migration(1)]` attribute on the base class.  It needs to go on the AddProductData class.  It's not inherited in a useful way - every class will have the same version and therefore it will fail on the second migration due to uniquness constraint.
3. Version IDs should be monotonically increasing but user-defined.  Some people, like me, space out IDs so that there is some fiddling room for developers to re-arrange versions prior to a release.  I use yyyyMMddXXXX where yyyyMMdd is year-month-day and XXXX is a four digit number with leading 0s.  I've never needed more than 9999 migrations in a given release, and I've been using FluentMigrator for years.  The most I've ever done was ~250 in a given day.
4. See below code: 

https://github.com/fluentmigrator/fluentmigrator/blob/27eb0110ff14b4d32aed7d316ee5caf4dda20716/src/FluentMigrator.Runner/MigrationRunnerBuilderExtensions.cs#L183

when you call ScanIn with: `.ScanIn(typeof(MyBaseClass).Assembly).For.Migrations())` it is passing the assembly, and the assembly must contain all migrations.  If that's not the case, e.g. if MyBaseClass is not in the same assembly as AddProductData, then you need to ensure the AddProductData assembly can load the MyBaseClass assembly in the same AssemblyLoadContext.
