### ISSUE TITLE
Tags not working correctly with runner in 3.2.4

### ISSUE THREAD

**Issue by mmiller678** [fluentmigrator/fluentmigrator#1211]
The runner is complaining that no migrations exist when a tag is specified.  I think is because its only picking up migrations with that tag, rather than migrations with the tag + migrations without any tags.

Exception
```
While executing migrations the following error was encountered: No migrations found,    at FluentMigrator.Runner.DefaultMigrationInformationLoader.FindMigrations(IMigrationSource source, IMigrationRunnerConventions conventions, String namespace, Boolean loadNestedNamespaces, String[] tagsToMatch, Boolean includeUntagged) in /home/travis/build/fluentmigrator/fluentmigra
tor/src/FluentMigrator.Runner/DefaultMigrationInformationLoader.cs:line 185 [D:\Source\Panda\trunk\build.targets]
D:\Source\Panda\trunk\Tools\packages\Weiss.MSBuild.1.2.54.1137\content\Weiss.Core.targets(91,5): error :    at FluentMigrator.Runner.DefaultMigrationInformationLoader.LoadMigrations() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/DefaultMigrationInformationLoader.cs:line 126 [D:\Source\Panda\trunk\build.targets]
```

**Comment by jzabroski** [comment]
I think this is a false positive.  This can happen is you run FluentMigrator.MSBuild 3.2.1 task with an assembly referencing FluentMigrator 3.2.4 nuget package.

I played around with reproducing the issue here: https://github.com/fluentmigrator/fluentmigrator/issues/1211

The only way, in my judgment, this can happen, is if the wrong assembly version is loaded.  Why it fails this way is a bit beyond me at the moment (midnight).  I will follow up with more, tomorrow maybe.

**Comment by mmiller678** [comment]
Agreed - this was a mistake on my part.  We can close this.
