### ISSUE TITLE
Rollback Transaction has appended at end of output file

### ISSUE THREAD

**Issue by karthi5589** [fluentmigrator/fluentmigrator#1220]
if we run the migration.cmd, Rollback Transaction has appended at end of the output file., this issue has occurred after upgraded to the version 2.0.7 and if we downgrade to 1.4.0 the issue resolved.

Note: the script has executed successfully.

![image](https://user-images.githubusercontent.com/29397437/79104330-facebb80-7d8b-11ea-9319-7262be42a6d6.png)

Please give me solution for this.

**Comment by jzabroski** [comment]
karthi5589 since you're on a super old version of FluentMigrator, I can suggest a couple of ways we can help:

1. What version of .NET Framework are you using?
2. To confirm, you're on FluentMigrator version 1.4 (released on 12/31/2014) and want to upgrade to FluentMigrator 2.0.7 (released on 4/27/2018)?
3. Have you gone through the release notes to see if there is a breaking change that impacts you?
4. Did you follow the upgrade guide from FluentMigrator 2.x to 3.y on FluentMigrator.github.io? Can you (try to) upgrade to FluentMigrator 3.y instead of 2.x?
5. Can you provide a minimal repro of the problem? Just posting script output isn't enough, as I have no way of knowing what you invoked to get there.

**Comment by karthi5589** [comment]
jzabrosk -  Thanks for reply.,
To answer your question.
1. we are using .NET Framework 4.6.2.
2. Already we have upgraded to 2.0.7 from 1.4.
3. yes
4. To upgrade again there are so many approvals are required. just simply we do not have option to upgrade., we have to fix this.
5. while migrating sql script there are no issues, migration happened as expected, but the problem is in output file "ROLLBACK TRANSACTION" has added simply.

**Comment by jzabroski** [comment]
Karthi5589,
#5 is not a repro. It's just the output file. Please provide source code and command line arguments. I wasn't involved in this project when 2.0 was around so I'll need your help to reproduce.

**Comment by karthi5589** [comment]
as below is the command arguments we follows, 
![image](https://user-images.githubusercontent.com/29397437/79122885-80676100-7db6-11ea-9b03-53865aa30d12.png)


to reproduce just downgrade/upgrade to version 2.0.7 then run migration part(commandline as mentioned above), then you will get the same problem in output file.

**Comment by jzabroski** [comment]
@karthi5589 This is not a repro.  Please provide a minimal repro with one Migration in a csproj that demonstrates the problem.  It would also be helpful instead of taking a screenshot if you could copy-paste the command line from your console so that you don't make me do extra work.  You have all this information available - this is a really old release you are asking for a hotfix for.  Please help.

**Comment by karthi5589** [comment]
@jzabroski - below are the command line added., I will try to take .csproj file

pushd %~dp0

C:\Users\XXX\.nuget\packages\fluentmigrator.tools\2.0.7\tools\net452\x86\Migrate.exe -a ".\bin\Debug\xxx.dll" --connectionString "Data Source=(local);Initial Catalog=xxx;Persist Security Info=True;Trusted_Connection=yes;Application Name=xxx" --provider SqlServer2012 --output --outputFilename  D:\test.sql

popd
@pause

**Comment by schambers** [comment]
Suggestion here is to upgrade to latest stable version of FM

In an effort to organize existing issues and due to age, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
