### ISSUE TITLE
PostgreSQL IsIdentity is creating the PK the old way?

### ISSUE THREAD

**Issue by KrisPetkov** [fluentmigrator/fluentmigrator#1256]
**Describe the question**
When I'm creating a new table for my PostgreSQL v12.2 and I set the **IsIdentity** property to **true** for the PK the column is created as `serial NOT NULL`. This is the old way of creating PK in PostgreSQL (before v10) and the new way is `int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY` 

Do you know how can I set this option so the PK can be created by the new way?

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform: .NET Core 3.1
 - FluentMigrator version: 3.2.6
 - FluentMigrator runner: "in-process runner"
 - Database Management System: Postgres v12.2

**Comment by jzabroski** [comment]
@KrisPetkov Is this causing an error, or is this a stylistic change you prefer?

**Comment by jzabroski** [comment]
The only Generator/Processor with robust version-specific support is SQL Server.  To change it, you would have to sub-class https://github.com/fluentmigrator/fluentmigrator/blob/5b44713448145572c70fcd283feb95ba7bcf0675/src/FluentMigrator.Runner.Postgres/Generators/Postgres/PostgresColumn.cs

and use in-process runner.

Alternatively, submit a patch that creates a new ProcessorId whereby people can opt-in to this behavior.  I'm not sure if a new ProcessorId is the right approach, though, given the forks of Postgres.  I need to think about this, or someone needs to help analyze it.  It's looking at the best way to do this that is the most time consuming.  The change itself is simple.

**Comment by KrisPetkov** [comment]
> The only Generator/Processor with robust version-specific support is SQL Server. To change it, you would have to sub-class

How can I use a sub-classed version of this class and tell FluentMigrator to use my sub-class instead of the base class?

> Alternatively, submit a patch that creates a new ProcessorId whereby people can opt-in to this behavior. I'm not sure if a new ProcessorId is the right approach, though, given the forks of Postgres. I need to think about this, or someone needs to help analyze it. It's looking at the best way to do this that is the most time consuming. The change itself is simple.

I'm sorry but I didn't quite catch this part with the ProcessorId.

P.S. I'm not much familiar with the architecture and the code of the FluentMigrator but I took a quick look. Is it possible to extend the **AddPostgres** extension method in **PostgresRunnerBuilderExtensions.cs** with an optional parameter (maybe a boolean such as **useSqlStandard=false** or introduce an **enum** so the users can opt their PostgreSQL version) and this optional parameter will have to be propagated down to **PostgresGenerator.cs** and finally to the **PostgresColumn.cs**. Based on this new parameter the generation of the PK can be controlled and maybe it will be useful in future if something else change.

**Comment by jzabroski** [comment]
> I'm sorry but I didn't quite catch this part with the ProcessorId.

FluentMigrator.DotNet.Cli nuget package, FluentMigrator.MSBuild nuget package, and FluentMigrator.Console nuget package.... all run off ProcessorId to select an object graph to use for interpreting migrations.  That object graph starts with a Processor and includes a Generator, but also details like Column model for how to pretty print as SQL the logical model FM provides.

When you switch to the In-Process ToolChain, processorid is basically irrelevant since you can build whatever object graph you want.

> Is it possible to extend the AddPostgres extension method in PostgresRunnerBuilderExtensions.cs with an optional parameter (maybe a boolean such as useSqlStandard=false1 or introduce an enum so the users can opt their PostgreSQL version) and this optional parameter will have to be propagated down to PostgresGenerator.cs and finally to the PostgresColumn.cs.

I'm not a huge fan of propagating such information around like that, especially boolean parameters.  For one, it alters the public interface in ways that make future end-users confused as to why that was even added five to ten years down the road.  For two, you already said that this wont work on Postgres 11, so it confuses people wanting to use functionality.  The Column printing logic should know its parent database, not the other way around.  Ideally we should have a metadata service that can be passed around to any part of the object graph, so that its' completely encapsulated and not exposed as some boolean value.  Then breaking changes are scoped to that interface and relatively easy to break and catch as compiler warnings and expose in release notes.

**Comment by jzabroski** [comment]
@KrisPetkov The list of ProcessorId's is listed here under Identifier column: https://fluentmigrator.github.io/#supported-databases

**Comment by jzabroski** [comment]
@KrisPetkov , it appears @sohra has written a full PR for this here: https://github.com/Sohra/fluentmigrator/tree/feature/postgres10identity

I generally like his approach and asked him to submit a PR.  He also fixed a minor issue in the test helper utilities.

It's possible down the line some of this logic can move into a more abstract interface, as Firebird, Postgres and SQL Server are pretty similar for many of these concepts.  But for now, it's best to keep it separate.

**Comment by jzabroski** [comment]
@KrisPetkov Here is @Sohra 's remarks: https://github.com/fluentmigrator/fluentmigrator/pull/1084#pullrequestreview-351910675

**Comment by KrisPetkov** [comment]
@jzabroski This is great and I think that this solution is pretty good. 
I hope that Sohra will make a PR and these changes will be merged.
I will close my issue and will keep track #1084 
Thank you for your time!

**Comment by jzabroski** [comment]
Thank you as well for the great discussion!  You help make projects like these worth the effort!
