### ISSUE TITLE
Connection string Password is not replaced 

### ISSUE THREAD

**Issue by benjaminrupp** [fluentmigrator/fluentmigrator#1283]
If password is at the end of the connection string and string does not end with ; the password is not replaced and is plaintext in the log file.

Classe: AppConfigConnectionStringReader.cs
Line: 39

Suggestion:
Replace regex with (PWD=|PASSWORD=)(([^;]*);|([^;]*)$)

**Comment by jzabroski** [comment]
Eww.  This code is nasty :)

https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator.Runner/Initialization/NetFramework/AppConfigConnectionStringReader.cs#L39

Without thinking about this too hard, why aren't we using DbConnectionStringBuilder?  Is the problem that we then don't know exactly which fields the raw connection string contained?

**Comment by jzabroski** [comment]
@benjaminrupp Submit a PR for your suggestion.  We should probably look into refactoring to use DbConnectionStringBuilder, though.  However, its a pretty glaring hole to potentially log the password to a file, so we should do an immediate hotfix.

**Comment by jzabroski** [comment]
See: https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnectionstringbuilder?view=netcore-3.1#:~:text=The%20DbConnectionStringBuilder%20performs%20no%20checks%20for%20valid%20key%2Fvalue%20pairs.&text=The%20SqlConnectionStringBuilder%20supports%20only%20key,pairs%20will%20throw%20an%20exception.

> Developers can create connection strings using either a strongly typed connection string builder class, or they can use the DbConnectionStringBuilder class. **The DbConnectionStringBuilder performs no checks for valid key/value pairs.** Therefore, it is possible using this class to create invalid connection strings. **The SqlConnectionStringBuilder supports only key/value pairs that are supported by SQL Server; trying to add invalid pairs will throw an exception**.

This probably explains why we don't use DbConnectionStringBuilder.

I guess the real solution is to construct a universe of key/value pairs for all providers, which seems like a lot of work, ergo why somebody did this regex magic.

**Comment by jzabroski** [comment]
@benjaminrupp Can you tell me what runner you're using and how you're getting the connection string?  I've tried to reproduce the issue, but am not able to.  I wrote a unit test that steps through it, and so it's possible I'm not configuring dependencies correctly.  The crux of it is if you load a connection string via configuration file, we never log the connection string, just the connection name.  My guess is this only happens if you pass in a connection string via the command line.

**Comment by benjaminrupp** [comment]
Hi jzabroski,

here is our init-code:
 private static IMigrationRunner GetMigrator(IApplicationContext applicationContext, string connectionString)
        {
            // Workaround to problem in password regex replacer in AppConfigConnectionStringReader of FluentMigrator
            if (!connectionString.EndsWith(@";"))
                connectionString += @";";

            FixWrongVersionNumbers(applicationContext, connectionString);

            var textWriter = new MigrationLoggingTextWriter();

            var serviceCollection = new ServiceCollection()
                .AddSingleton<ILoggerProvider>(new SqlScriptFluentMigratorLoggerProvider(textWriter))
                .Configure<SqlScriptFluentMigratorLoggerOptions>(
                    opt =>
                    {
                        opt.ShowSql = true;
                        opt.ShowElapsedTime = true;
                        opt.OutputGoBetweenStatements = true;
                    })
                .AddFluentMigratorCore()
                .AddSingleton(applicationContext)
                .ConfigureRunner(
                    builder => builder
                        .AddDatabase(applicationContext.SessionProvider)
                        .ConfigureGlobalProcessorOptions(
                            go =>
                            {
                                go.PreviewOnly = false;
                                go.Timeout = TimeSpan.FromMinutes(60);
                            })
                        .WithGlobalConnectionString(connectionString)
                        .WithMigrationsIn(typeof(UserMap).Assembly));

            var serviceProvider = serviceCollection.BuildServiceProvider();

            return serviceProvider.GetRequiredService<IMigrationRunner>();
        }

I hope this helps you.

Best regards

Benjamin

**Comment by jzabroski** [comment]
Got it.  This only happens if you pass in a raw connection string instead of a connection string name.  I suppose this would happen if you're using an external loader like Hashicorp Vault to load the sensitive information, as the default connection string name loader only uses .NET specific chain of responsibility.

**Comment by jzabroski** [comment]
@benjaminrupp I think your regex is incorrect. It's subtle, but because of greedy quantification, you have to put the $ at the end of each sub-token, because each sub-token is its own DFA string. I also labeled the capture groups so it's a bit clearer (if a lot longer).  Here is my attempt at it.

### Pattern
```
^.*(?<Key>PWD=|PASSWORD=)(?<OptionalValue>((?<None>(;|;$|;*$))|(?<Value>(([^;].*)))))
```
### Input
```
Password=pass@123
Password=pass@123;
Password=pass@123;;
Password=
Password=;
Password=;;
```

I plugged it into http://regexstorm.net/tester

![image](https://user-images.githubusercontent.com/447485/87169142-87aae780-c29d-11ea-9505-56315424dbae.png)

**Comment by jzabroski** [comment]
Updated regex one last time to include additional test case.

**Comment by jzabroski** [comment]
@benjaminrupp On Friday, I fixed this locally using the above regex, but want to clean up the test before I merge it.  Frankly, I was surprised to see there is basically no deep structural testing of logging in the code base.  I explored several different ways to write our first "semantic logging tests."  One is using a library called MELT that mocks MS DI ILoggerProvider, but I am not sure I love adding a dependency just for testing logging.  On the other hand, the big pro to MELT is it captures each individual log statement as an entry.
