### ISSUE TITLE
Investigate NugetCommand@2 Custom -SkipDuplicate

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1305]
**Describe the bug**
Today, while releasing FluentMigrator 3.2.8, we ran into a partial failure in the deploy to nuget.org.

We may want to use the nuget.exe -SkipDuplicate flag to allow for partial failure.

**To Reproduce**
See Release-40 and Release-41 for various efforts to fix the deploy.

**Expected behavior**
If there is a partial failure on deployment, continue to upload packages.  Should be able to re-run nuget.org Deploy Task many times as if it were idempotent.

CC @eloekset

**Comment by jzabroski** [comment]
I was able to get it to work by forcibly excluding the one FluentMigrator.3.2.8.nupkg https://dev.azure.com/fluentmigrator/fluentmigrator/_releaseProgress?releaseId=41&_a=release-environment-logs&environmentId=155

**Comment by eloekset** [comment]
Looks like jzabroski already found the solution using -SkipDuplicate. https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push

Will just have to modify the task and see if it works as expected the next time we run into a situation like this. Will update the issue once the release task is changed.

**Comment by jzabroski** [comment]
@eloekset  Note, I did not get it to work when I tried.  The main things I am confused by are: when using nuget Custom task in ADO, how do you pass in the glob of files to push?  How do you pass in the -SkipDuplicates parameter?

**Comment by eloekset** [comment]
It's easy to support -SkipDuplicate on an internal feed, but when **External NuGet server** (like NuGet.org) is selected, the option goes away. I'm afraid we'll have to switch to **custom** command instead of **push** we'll have do go some rounds before the nifty details are configured correctly.
![image](https://user-images.githubusercontent.com/791721/88438094-2db33180-ce08-11ea-9511-33d86cb4cdb1.png)
![image](https://user-images.githubusercontent.com/791721/88438112-33a91280-ce08-11ea-8f5e-64ab6764bbbf.png)

But you made it work somehow without the `-SkipDuplicate` flag? If so, do you think it will work the next time we run into this issue, or should be try switching to **custom** - or just invoke nuget.exe from a PowerShell script instead?

**Comment by eloekset** [comment]
Oh, I see your comment now. Forcibly excluding a package from the script sounds a bit too cumbersome. I think we should try using a custom command then. It will probably take some releases to have it correctly setup, but as long as we don't have anything that needs to be released in a hurry, we should be fine with that.

**Comment by jzabroski** [comment]
I would create a second release pipeline with two dummy packages.  FluentMigrator.Dummy1, FluentMigrator.Dummy2.  You can unlist those packages in nuget.org for end-to-end integration test.  Just define them both as Tools in the csproj and pack them.  That would avoid creating spurious releases in the main channel.  Do you agree?

**Comment by eloekset** [comment]
I think this command is correct, but it's hard to know unless we test it with some other feed maybe. Don't necessarily have to deploy to nuget.org.
`push $(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg -src NuGet.org -SkipDuplicate`

Two things that I'm not sure of:
1. Will the `-src` parameter understand that the value `NuGet.org` represents the name of the service connection with access token setup? I think so, since [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-nuget) says that the **Connection name** value can be used by **task properties**.
2. Will the correct feed be used for symbol packages automatically? I have no experience with symbol packages in separate feeds.

I will have to continue with this another day. I've documented my current thoughts for later here now, so I won't save the changes to the release pipeline yet.

**Comment by eloekset** [comment]
Looking into this again almost four years later... I tested my theory from 2020 in a private project to verify that I can push to NuGet.org that way, and also redeploy the same release without any errors. However, I didn't have any symbol packages to test with in my simple test project.

I've updated the release pipeline and disabled the previous task to push to NuGet.org. I also had to create a new API Key on the fluent-migrator organization at NuGet.org, since the old one had expired and I don't know who's got it.

![image](https://github.com/fluentmigrator/fluentmigrator/assets/791721/3b24b3ff-4fe2-4fee-9f6b-6fdcfd35bcf0)

I think this will work just fine, but we'll have to see on the next release.

**Comment by jzabroski** [comment]
I had the key saved in Dashlane

**Comment by jzabroski** [comment]
Do you happen to know why the 5.1 Github Release didn't trigger a build in
ado?

Tried to get Microsoft help and they were not helpful. Debating renaming
default branch back to master as I think that will sadly fix it.

**Comment by jzabroski** [comment]
The new CMD.exe approach did not work - it says: `File does not exist (D:\a\r1\a/**/*.nupkg;!D:\a\r1\a/**/*.symbols.nupkg)` : 

```
2024-02-19T17:22:04.7843615Z ##[section]Starting: Command Line Script
2024-02-19T17:22:04.7960888Z ==============================================================================
2024-02-19T17:22:04.7961053Z Task         : Command line
2024-02-19T17:22:04.7961139Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2024-02-19T17:22:04.7961259Z Version      : 2.231.1
2024-02-19T17:22:04.7961323Z Author       : Microsoft Corporation
2024-02-19T17:22:04.7961398Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2024-02-19T17:22:04.7961528Z ==============================================================================
2024-02-19T17:22:05.7132161Z Generating script.
2024-02-19T17:22:05.7227900Z Script contents: shell
2024-02-19T17:22:05.7236642Z nuget push D:\a\r1\a/**/*.nupkg;!D:\a\r1\a/**/*.symbols.nupkg -ApiKey *** -src NuGet.org -SkipDuplicate
2024-02-19T17:22:05.7551086Z ========================== Starting Command Output ===========================
2024-02-19T17:22:05.7784386Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\232c7b86-b90e-437f-a8a5-66c12600c0d8.cmd""
2024-02-19T17:22:07.7376461Z File does not exist (D:\a\r1\a/**/*.nupkg;!D:\a\r1\a/**/*.symbols.nupkg).
2024-02-19T17:22:07.8233909Z ##[error]Cmd.exe exited with code '1'.
2024-02-19T17:22:07.9110763Z ##[section]Finishing: Command Line Script
```

**Comment by jzabroski** [comment]
I rolled back the change for 5.1.0 release.  No harm as the deployment did not fail midway through pushing.

**Comment by jzabroski** [comment]
See my private email on this.
