### ISSUE TITLE
Automate updating fluentmigrator/documentation git submodules

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1395]
@eloekset Any chance we can automate updating this whenever we publish a release to nuget.org?

![image](https://user-images.githubusercontent.com/447485/102630474-9635de80-411a-11eb-8638-414c4a55500e.png)

**Comment by jzabroski** [comment]
I think it's as simple as the following sequence (which is what I did tonight to manaully do this):

```powershell
git clone https://github.com/fluentmigrator/documentation.git
cd documentation
git submodule update --remote
git fetch upstream
git push origin
```

**Comment by jzabroski** [comment]
actually, i see we do update it every time we deploy the documentation: https://github.com/fluentmigrator/documentation/blob/master/azure-pipelines.yml#L17

**Comment by jzabroski** [comment]
@eloekset I'm a little confused why its not updating the latest docs.  Thankfully, the docs are relatively up-to-date.

**Comment by fubar-coder** [comment]
I'm confused too. Maybe there's an additional checkout needed?

**Comment by eloekset** [comment]
Sorry for not replying for so many years. 

I've read a bit about submodules now, and as far as I understand, the `git submodule update --init --recursive` command should update to the latest commit on those branches that are configured. But I never use submodules elsewhere, so I'm not familiar with how it works. If we know that it still doesn't work, maybe adding a `--remote` will fix it.

Should we add submodules for more branches now that the latest version no longer is 3.x?
![image](https://github.com/fluentmigrator/fluentmigrator/assets/791721/434c8e35-9431-4d8d-8008-17faf8c5eb7e)

We have **main**, **archive/2.x** and **archive/4.x** branches, but no **archive/3.x** branch. So maybe we need to create an **archive/3.x** branch for the current commit of that submodule in the documentation repo? https://github.com/fluentmigrator/fluentmigrator/tree/e4b381bad998396fffc8d006ab6c9211d60f085c

I guess we have renamed **master** to **main** some time after that documentation repo added a submodule for 3.x, since the .gitmodules file now refers to a branch that doesn't exist:
![image](https://github.com/fluentmigrator/fluentmigrator/assets/791721/7c805929-1467-412c-bf17-71241ff6465b)

**Comment by eloekset** [comment]
@jzabroski I did as I proposed in the comment above and added you as a reviewer on this PR https://github.com/fluentmigrator/documentation/pull/70 

I'm not 100% sure that I do the right things, but it looks ok to me when I go through the all files and see how the documentation repo is built up.

**Comment by jzabroski** [comment]
Thank you so much!

**Comment by eloekset** [comment]
Related to https://github.com/fluentmigrator/documentation/issues/71 and closed by https://github.com/fluentmigrator/documentation/pull/72

**Comment by jzabroski** [comment]
Wow, thank you!
