### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.2.2.0 ...

### ISSUE THREAD

**Issue by d-vs** [fluentmigrator/fluentmigrator#1406]
**Describe the bug**
I've created a .Net Core 3.1 project, containing fluent migrations. The project compiles to an .exe (it's a console app). When attempting to run migrations contained in the assembly, using the dotnet-fm tool, the following exception occurs:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

**To Reproduce**
Description explains it all.

**Expected behavior**
The migrations are run successfully.

**Information (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Platform .NET Core 3.1
 - FluentMigrator version 3.2.11
 - FluentMigrator runner FluentMigrator.DotNet.Cli
 - Database Management System SQLServer
 - Database Management System Version SQL Server 2019 Standard Edition

**Comment by jzabroski** [comment]
For now, the only workaround is to add a DirtyAssemblyResolveHelper that helps the run-time out by doing an ad-hoc binding redirect using your bin directory as the probing path. Here's an example implementation.  It's called Dirty because ideally there would not be a need for this.  But with this, you can use the .NET Global CLI Tool FluentMigrator.DotNet.Cli _and_ you can even run net48 assemblies through the CLI tool.  Crazy, huh?  The risk is that since it is dirty, unless you test your execution paths in lower environments, you probably can't predict what it will do, especially if you use a lot of third party dependencies in your Migrations.dll
 https://github.com/dotnet/BenchmarkDotNet/blob/852bb8cd9c2ac2530866dc53723c5f2ce3d411fa/src/BenchmarkDotNet/Helpers/DirtyAssemblyResolveHelper.cs#L18

**Comment by jzabroski** [comment]
Note, DirtyAssemblyResolveHelper would also probably ideally use MetadataLoadContext to help with probing, but I haven't tried it and it probably isn't strictly required.

**Comment by jzabroski** [comment]
@fubar-coder What are your thoughts on adding a DirtyAssemblyResolveHelper switch to FluentMigrator.DotNet.Cli until I finish and merge #1072 ?  I think this would be a low effort workaround vs. the amount of work to merge back in my changes since it's drifted a lot from master since May.

**Comment by d-vs** [comment]
@jzabroski thanks for the swift response. Will use the in-process runner method until there is proper support. Will leave you to close this issue as you see fit.

**Comment by fubar-coder** [comment]
@jzabroski Seems reasonable. I definitely makes sense to have a working workaround for this issue.

**Comment by OneThatWalks** [comment]
What might be a workaround for out of process runners?

Our team has been using powershell to execute migrate.exe based on local machine/user nuget package location.  We are struggling with how we can get an out of process runner to work with Octopus Deploy and not be so coupled to file paths.

Somehow the dotnet-fm tool worked locally and I must have changed something because now I get this System.Runtime issue

Project targets netcoreapp3.1

**Comment by jzabroski** [comment]
Create a MainteanceMigration that runs BeforeAll and in the `Up()` method, just call a "dirty" assembly resolve using the signature `Assembly AssemblyResolve( object sender, ResolveEventArgs args)` that just matches on the assembly name for System assemblies.

**Comment by jzabroski** [comment]
If you want to submit a PR for this, I would _love_ that.  Our build is currently broken due to an unknown issue and that is one reason I haven't had time to create a PR myself (on top of being really busy with work + life).

**Comment by OneThatWalks** [comment]
@jzabroski I made a mvp to see if this is what you are talking about.  When you get a chance, check out [Program.cs](https://github.com/OneThatWalks/fluentmigrator/blob/master/src/FluentMigrator.DotNet.Cli/Program.cs) in my fork.

I tested this against my migration in the absence of extra time to create a sample project.
The results when debugging is that System.Runtime is loaded from the Runtime Environment and FluentMigrator/FluentMigrator.Abstractions is loaded from the bin.

**Comment by jzabroski** [comment]
@OneThatWalks That's exactly what I had in mind.  We can improve it slightly by using MetadataLoadContext to sneak peak at the assemblies, but I am 99% sure people will be happy with this solution.  Remaining blocking is #1416 which I have been working on a bit (if you're familiar with AzureDevOps, feel free to take a look at my notes so far.)

**Comment by OneThatWalks** [comment]
We also use Azure Dev Ops I'll have a look, different beast and I sympathize.

**Comment by OneThatWalks** [comment]
@jzabroski before I start for the day do you have suggestions on what I should change pre PR, you had some ideas you were thninking in relation to the MetadataLoadContext api.  It seems like this might be a temporary solution until the tool is updated to support dotnet core 3.1+.

**Comment by jzabroski** [comment]
Ship it

**Comment by schambers** [comment]
This seems to have been merged successfully. Closing this
