### ISSUE TITLE
Sqlite Identity column is required to be int32

### ISSUE THREAD

**Issue by zelenij** [fluentmigrator/fluentmigrator#1456]
**Describe the bug**

Sqlite code generator seems to require that Identity column must be Int32 - in which case it will be defined as autoincrement. I can't find any reason for this in the documentation.  In fact, the sqlite doc says that primary autoincrement key will be mapped to the hidden ROWID column, which is 64 bit.  So there is no reason that the code generator shouldn't accept Int64 at least.  The relevant code line:

https://github.com/fluentmigrator/fluentmigrator/blob/9c87d698b161b3a1bb596a5624c02891a64459c5/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteColumn.cs#L34

Sqlite doc:

https://sqlite.org/autoinc.html

**To Reproduce**
In a migration define a column like this:

```
        this.Create.Table("TestTable")
            .WithColumn("Id").AsInt64().PrimaryKey().Identity()
```

And run a migration for Sqlite

**Expected behavior**

New table successfully generated.

**Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Platform .net5
 - FluentMigrator version latest
 - FluentMigrator runner [  FluentMigrator.Console ]
 - Database Management System [ SQLite ]
 - Database Management System Version [ N/A ]

**Comment by fubar-coder** [comment]
This is somewhat confusing, and might indeed be a problem when you want to use the same migration for multiple databases and you expect more than 2 billion rows in a table.

If you're using the migration only with SQLite, then this is not a problem at all, because SQLite doesn't distinguish between multiple integer types of different widths. In other words: SQLite only knows "INTEGER", "REAL", etc..., but other types (e.g. "INT8", "DOUBLE") are mapped to the 5 basic types SQLite knows about: [INTEGER, TEXT, BLOB, REAL, NUMERIC](https://www.sqlite.org/datatype3.html)

**Comment by zelenij** [comment]
This is exactly my scenario - I expect a lot of record in production, where I'm targeting PostgreSQL, but for local testing I'm fine with Sqlite for now.  Ideally I'd want to use identical migrations as far as possible.

**Comment by zelenij** [comment]
I'll be happy to create a PR to address this problem.

**Comment by jzabroski** [comment]
Please create.

**Comment by jzabroski** [comment]
@zelenij Just wondering if you do plan to create a PR here.  I am looking at overhauling the SqliteGenerator

**Comment by zelenij** [comment]
It's not too urgent for me, so feel free to overhaul...
