### ISSUE TITLE
Running the same set of migrations against multiple databases

### ISSUE THREAD

**Issue by VeldoraStormDragon** [fluentmigrator/fluentmigrator#1550]
Hi there,

I have a requirement to apply migrations on multiple databases and of them have the same schema.  The number of databases to apply migrations on is over 500.  Here is what my implementation is.

     public class MigrationService
     {
        private readonly string _connectionString;

        public MigrationService(string connectionString)
        {
            _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
        }

        public void RunMigrations()
        {
            var provider = ConfigureProvider();

            using (var scope = provider.CreateScope())
            {
                UpdateDatabase(scope.ServiceProvider);
            }
        }

        private IServiceProvider ConfigureProvider()
        {
            var collection = new ServiceCollection()
                .AddFluentMigratorCore()
                .ConfigureRunner(
                    r => r
                        .AddSqlServer2016()
                        .WithGlobalConnectionString(_connectionString)
                        .ScanIn(GetType().Assembly)
                        .For.All())
                .BuildServiceProvider(false);

            return collection;
        }

        private void UpdateDatabase(IServiceProvider provider)
        {
            var runner = provider.GetRequiredService<IMigrationRunner>();
            runner.MigrateUp();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            string[] connectionStrings = new string[500];
            // initialize the connection strings..

            Parallel.ForEach(connectionStrings, new ParallelOptions { MaxDegreeOfParallelism = 10 }, con =>
            {
                new MigrationService(con).RunMigrations();
            });
        }
     }

**Questions**:
    

1. Is there a more elegant way to handle this kind of requirement that doesn't involve re-register the migration runner every time with a different connection string?  Basically I'm looking for a way to resolve IMigrationRunner with a specific connection string.
2. We actually implement this as an Azure Durable function and instead of doing the parallel for-each loop like in this sample, we start a new Task to create a new MigrationService to handle one dataabse.  However we do limit the number of the concurrent tasks to 10 just like in this example.  However, we constantly run into an error that we have maxed out the outbound TCP connection limits.  I wonder if it's something specific with the Azure Durable function or my setup is leaving database connections open somehow.  It seems that calling await Task.Delay(...) after the RunMigrations() call to delay things a bit before the task completion seems to help.  Yet it is very strange that I keep hitting the 600 outbound connection limits of the Azure Function when I'm migrating only 10 databases at a time.

**Comment by jzabroski** [comment]
> 2\. However, we constantly run into an error that we have maxed out the outbound TCP connection limits.

That's a windows setting. https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust

I don't see why 500 connections would do this, but I also don't know much about Azure. I am not a big fan of Azure as Microsoft employees generally ignored my feedback on Azure Functions poor architecture with regards to in-place upgrades and they cost me a lot of hours of my personal time replying to _their_ customers and explaining the problem was on Microsoft's side not mine.  So, despite the fact I work with Microsoft Technologies, I am not really your guy to give advice on Azure Functions currently.  I recall Azure Durable Functions are limited in that you can't run them inside a docker image, and vaguely recall recommending to someone they use the Durable Task Framework over Azure Functions regular via docker image instead.

**Comment by jzabroski** [comment]
> 1. Is there a more elegant way to handle this kind of requirement that doesn't involve re-register the migration runner every time with a different connection string?  Basically I'm looking for a way to resolve IMigrationRunner with a specific connection string.

I would only call `BuildServiceProvider` once per AppDomain or AssemblyLoadContext (if you have multiple contexts - not typical in my experience).

I would resolve IMigrationService once per inner loop call, and have each instance get its own IMigrationRunner and therefore DbContext/SqlConnection.

I would pass the connection string in via `RunMigrations(string connectionString);` rather than your approach of passing it in via the constructor.  It is a bit more flexible and makes it easier to reason about the lifetime scope of what a IMigrationService "owns".

**Comment by jzabroski** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp#connection-limit says the limit is 600 connections.

I am not sure how they count connections, but the trivial way to determine this would be to set-up a SQL Server Profiler trace with your specific Application Name in the connection string and then you can dump that trace to a table and see how many unique connections are made.  I believe each connection should have its own ClientConnectionId.  Another approach would be to set the connection pool size to some embarrassingly low number for debugging purposes only, and you can see where it stalls out waiting for a connection from the connection pool.
