### ISSUE TITLE
Error while trying to run Migrate.exe on .NET 6 | Could not load file or assembly

### ISSUE THREAD

**Issue by rom5jp** [fluentmigrator/fluentmigrator#1557]
**Describe the bug**
I'm trying to run a `rollback` command via Migrate.exe but I receive the following error message: "!!! Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

**To Reproduce**
Run the following command: `.\Migrate.exe migrate --allowDirtyAssemblies --conn "Server=xxx;Port=xxx;Database=xxx;user=xxx;password=xxx;" --provider mysql --assembly "C:\...\bin\Debug\net6.0\myproject.dll" --task rollback --output --outputFilename output.sql`

**Expected behavior**
Execute the command successfully.

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform: .NET 6
 - FluentMigrator version: 3.3.2
 - FluentMigrator runner: FluentMigrator.Console 3.3.2
 - Database Management System: MySQL
 - Database Management System: MySQL 8.0.21

**Additional context**
I came through this [closed issue](https://github.com/fluentmigrator/fluentmigrator/issues/1428).

**Comment by fubar-coder** [comment]
It seems that you've already used the `--allowDirtyAssemblies` flag. @jzabroski Any idea?

**Comment by jzabroski** [comment]
`--allowDirtyAssemblies` is not defined for Migrate.exe :(

I would recommend using FluentMigrator.DotNet.Cli .  Migrate.exe is a legacy tool.

**Comment by jzabroski** [comment]
@fubar-coder (Off-topic) At what point do you think we should just stop shipping Migrate.exe?  The main reason I ship it today is that FluentMigrator.MSBuild does not ship all associated binaries, and so I copy FluentMigrator.Console package binaries into my MSBuild tool folder so that I can get MSBuild console colors when I run MSBuild tasks.  I think we can fix FluentMigrator.MSBuild by packaging a FluentMigrator.MSBuild.BatteriesIncluded version that ships all the stuff the Console package ships.  Is there another approach I am not thinking of?
