### ISSUE TITLE
LiteDB support

### ISSUE THREAD

**Issue by suatsuphi** [fluentmigrator/fluentmigrator#1637]
Hi,

Could you add litedatabase support ? https://www.litedb.org/

**Comment by jzabroski** [comment]
You can always just use the regular ODBC support and generic driver to talk to litedb.   This is also the same way you could add Trino support, for example: https://trino.io/docs/current/language/sql-support.html

I personally don't plan to add support for it, but you could also submit a PR to make it happen.

**Comment by fubar-coder** [comment]
LiteDB is a NoSQL database and FluentMigrator doesn't support those (yet).

**Comment by jzabroski** [comment]
@fubar-coder You are right. It supports SQL but not through the System.Data API, so the generic processor / generator isn't useful. Confirmed via reading https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Client/Database/LiteRepository.cs

It is still PLAUSIBLY possible to basically use LITEDB with FluentMigrator, but they would have to use some connectionless mode, generate a script, and the LiteDB SqlParser would have to accept our generic processor command patterns.

I'm not recommending this, per say, just suggesting it may be viable if for some reason you really want to use FluentMigrator.

That said, here is a brain dump:

 I have started looking at NoSQL support - not just for databases but various data formats. For example, Chr.Avro nuget package is an alternative implementation of Apache.Avro nuget package. Both implement the Avro data format that is commonly the storage format for NoSQL databases like Hadoop. However, the "sexy" reason to use C.H. Robinson's nuget package over the Apache package is it seamlessly integrates with [Confluent's Apache Kafka and Schema Registry client](https://github.com/confluentinc/confluent-kafka-dotnet). 

The main blocker here is, again, there is no System.Data namespace for NoSQL. Some of them can talk to it, but most cannot. Even if there was, the concepts across these NoSQL DB can be fairly inconsistent. For example, Kafka has topics, topic partitions, and topic offsets. Without these concepts, Kafka is fairly useless. But these aren't topics on most NoSQL DB because most are just CRUD stores, not event streamers. And so the most common partition is Schema VS. Schema-less. In the Schema-less case, it would be nice if a tool at least generated validation rules on save that are c# data type aware, so we are not just hacking on strings. 

And yet, if you look at enterprise architecture, Kafka is what might feed various downstream data marts. Then people stitch it all back together again via GraphQL and microservices, lol.
