### ISSUE TITLE
Limit SQLite type mapping changes in 5.0 possibly breaking change?

### ISSUE THREAD

**Issue by nickeeex** [fluentmigrator/fluentmigrator#1722]
After updating to 5.0 i noticed that Dapper when used with System.Data.Sqlite breaks because of type mapping changes for SQlite
For example when doing a simple query:
`connection.Query<(Guid Id, int Version, string Data)` 
Now Id is of type TEXT and the Dapper SqlMapper does not know how to handle the conversion. 

Is there any built in way to revert back to the old functionality (while still using the new dependency injection)

https://github.com/fluentmigrator/fluentmigrator/pull/1581

One workardound was to modify existing migrations to create the columns AsCustom("OLDTYPE")
Luckily we had separate migrations for SQlite/sql server/etc

This could also be fixed on dapper side by implementing custom TypeHandler but that got complicated when the underlying db could be sqlite, sql server, postgres etc and the TypeHandlers are registered globally.

**Comment by jzabroski** [comment]
Thank you, this is a lot clearer.  I have one follow-up question.

How does Dapper handle System.Data.Sqlite given the original PRs comments about type affinity?  It seems like the short-term fix is to support both System.Data.Sqlite and Microsoft.Data.SQLite: https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/compare#data-types

If I understand this correctly, I think part of the problem may be that your particular SQLite db has a type affinity to an arbitrary type that doesnt really exist?  So, if you created your db with Microsoft.Data.SQLite driver, and you used non-standard type names, and now want to talk to it with System.Data.Sqlite, is that a problem?  Just trying to fully grasp the problem before I provide a fix, which should be pretty easy once I understand the exact root cause.

**Comment by nickeeex** [comment]
We've always used System.Data.Sqlite. The older version of FluentMigrator just seemed to create the columns with the arbitery types (in our case UNIQUEIDENTIFIER and DATETIME). I think System.Data.Sqlite automatically maps these arbitery types to corresponding .NET types. Haven't used any special connection string when creating the sqlite databases so this was just mostly OOTB functionality. I do not think this has anything to do with dapper directly. 

The workaround was pretty simple instead of AsGuid() I used AsCustom("UNIQUEIDENTIFIER") to revert back to the pre 5.0 functionality and that made the db look the same as previously.

**Comment by jzabroski** [comment]
What does `SELECT typeof(Id) FROM YourTable` say the type is, assuming Id is the `Guid Id` parameter column name?

**Comment by nickeeex** [comment]
> What does SELECT typeof(Id) FROM YourTable say the type is, assuming Id is the Guid Id parameter column name?

The type is Blob, seems like you are correct in your assumptions, also checked with a sqlite browser and the Guid is stored in binary format.

This is what the SQLite reader has defined for the columns:
![image](https://github.com/fluentmigrator/fluentmigrator/assets/6636662/49ae3061-b3a9-478b-8912-eb1fab9a751d)

After some debugging i found this under System.Data.Sqlite SQLiteConverters
![image](https://github.com/fluentmigrator/fluentmigrator/assets/6636662/0592a7ab-8910-44d8-a999-782d3dd20fef)

Here is the full list of the System.Data.Sqlite type mappings:
https://github.com/haf/System.Data.SQLite/blob/8d2e5027723654e97d2ad208b9a076da496eee79/System.Data.SQLite/SQLiteConvert.cs#L1644

**Comment by workgroupengineering** [comment]
Is there a way to customize SQLite column mapping without recompiling Fluentmigrator?

**Comment by jzabroski** [comment]
No, we have #1063 as a backlog item.  I'm actually pretty close to making that a feature.  I'm working on stuff right now in my local to make progress on idempotent migrations first.
