### ISSUE TITLE
Consider merging with Entity.Migrations

### ISSUE THREAD

**Issue by mirhagk** [fluentmigrator/fluentmigrator#486]
Entity framework is an open source ORM. As part of the process, it includes the ability to generate a database from code, and the ability to create migration scripts.

The migration scripts use it's own internal Entity.Migrations.DBMigration class to do so, and this class's purpose and use is very similar to fluentmigrator's class, with the up and down methods and some functions to generate the required components.

It seems rather silly to have 2 open source frameworks being developed without any of the code being shared or reused, so I recommend looking at [their code](https://entityframework.codeplex.com/SourceControl/latest#src/EntityFramework/Migrations/DbMigration.cs) and seeing if anything can be used in FluentMigrator, or if they are missing anything FluentMigrator has (in which case it could be added to EntityFramework).

It'd be neat to have support to have Entity Framework generate migration scripts that use Fluent Migrator's API as well as it's own.

**Comment by KrisPetkov** [comment]
After 6 years and a half are there any plans for that? I bet that EF code is quite different now. This functionality will be quite handy for starting and rapidly developed projects which are using the Code First approach.

**Comment by jzabroski** [comment]
@KrisPetkov  First, this is out of our hands.

Second, to step on a soap box for a moment:
I think that FluentMigrator supports a superset of all SQL database migrations, not just those using EF.  There are multiple migration frameworks in .NET, but FluentMigrator is one of the more actively maintained projects with the help of myself, @BigYellowHammer , @eloekset and @fubar-coder .

The main reason not to use EF code for code-first migrations is because you can create tables for any schema with FluentMigrator.  With EF code-first, you have to explicitly map many-to-many relationships which implies having an extra Id column in the intermediary entity, and I have personally reported bugs with EFCore that they've tried to fix several times and failed, namely around Table-Per-Hierarchy class models using Discriminators.

Basically, if you don't value representation independence, then its obvious to just use EF.  If you do value representation independence and targeting arbitrarily many databases and plug-in different data access layers like Dapper, RepoDB, NHibernate, etc. then FluentMigrator is definitely for you.  Lastly, in my experience, FluentMigrator is superior for data migrations when cleaning up brownfield database projects.

In terms of unifying FluentMigrator with EFCore, Source Generators might provide a way to automatically generate those mappings, but there are some blocking issues we have on our roadmap before it makes sense to use Source Generators.  If you want to discuss and consider taking on some of those items, that would be awesome and add hundreds of thousands of notional dollars of value across the FluentMigrator community.

**Comment by KrisPetkov** [comment]
@jzabroski Thank you for the comprehensive answer!
I also think that FluentMigrator is a superior product. 
And with my question I was targeting the source generators only (my mistake that I didn't specify it better) .

I'd be happy to help with the issues but first I have to finish with another two projects otherwise I will not be able to pay any attention to the issues.

**Comment by jzabroski** [comment]
Can you please open a new issue and link your original comment in that new issue, so that you are the issue owner?  It will then let you navigate in GitHub to your global open Issues and let you track across all projects what you want to get done.

I feel you.  My biggest problem is I have endless ideas and can only type 60-70 wpm.
