### ISSUE TITLE
ZombieCheck "The SqlTransaction has completed; it is no longer usable" 

### ISSUE THREAD

**Issue by matteomigliore** [fluentmigrator/fluentmigrator#608]
Hi,
launching the migration on remote SQL Azure I obtain the exception in the title, in local all works.

I launched many migrations before the last two, but these don't run, so I've to download the DB, migrate it locally and than upload and import again.

Thank you.

**Comment by tommarien** [comment]
@matteomigliore Hi Matteo

Have you tried upping the command timeout  see https://github.com/schambers/fluentmigrator/wiki/Command-Line-Runner-Options#--timeoutvalue-optional ?

**Comment by matteomigliore** [comment]
Hi @tommarien, yes thank you.

**Comment by tommarien** [comment]
@matteomigliore Can i consider this issue as closed ?

**Comment by matteomigliore** [comment]
No, the problem persists. Seems to be related with Execute.WithConnection, a "big" amount of insert/update/delete causes the issue.

**Comment by tommarien** [comment]
@matteomigliore Have you tried highering connectionTimeout on the connection ?

**Comment by matteomigliore** [comment]
Yes, but it does not work.

**Comment by tommarien** [comment]
@matteomigliore Then i guess it probably has to do with transaction timeout but i am not sure on this one.

**Comment by john20xdoe** [comment]
also encountered this message while deploying in an Azure datacenter. the platform I am using is Serenity (https://github.com/volkanceylan/Serenity), which uses fluentmigrator to run migrations during startup. I have isolated the code to when it Executes the Runner. I have also tried upping the Timeout parameter but it does not fix the issue.

**Comment by colotiline** [comment]
Same situation. 

Specs:
1. SQL Server 2008 R2. 
2. Windows Server 2008R2.
3. Adding a persisted MD5 calculated column on ~1-2m rows in 8-10 tables.

**Comment by soulomoon** [comment]
same here 
Specs:

1 SQL Server 2008 R2.
2 Windows Server 2008R2.
3 5~6m rows from one table to another

**Comment by alemaitour** [comment]
If you split all scripts to two or three .cs files, solves the problem ?

**Comment by fubar-coder** [comment]
Closed due to inactivity

**Comment by jzabroski** [comment]
This issue is usually caused by a bad DDL statement.  Althought TSQL DDL is transactional, sometimes it can enter weird state.

**Comment by BrunoJuchli** [comment]
This symptom can be easily triggered by:

        this.Execute.WithConnection((connection, transaction) => transaction.Rollback());

Now I'd suspect while it compiles, this violates the "contract" of FluentMigrator, i.E. we just shouldn't use it like that.
In our case it's a bit more complex. We are (were) using a 3rd party library to compile & execute SQL. And that library rollbacked the transaction in case of a failure (`Exception`).
Now the problem with FluentMigrator is, it throws an exception like:

`System.InvalidOperationException
This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Rollback()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.RollbackTransaction()
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.RollbackTransaction()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.Dispose(Boolean isDisposing)
   at FluentMigrator.Runner.Processors.ProcessorBase.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope

And the original exception is lost.
It'd be nice if the exception message would be enriched with some information like "The Transaction has already been rolled back. Make sure you don't rollback the transaction - leave this to FluentMigrator" or something like that.

**Comment by jzabroski** [comment]
@BrunoJuchli I don't agree with you here.  I am an expert in SQL Server, and the problem is not that the original exception is lost.  The problem is that you need to log, at the SqlConnection level, all "user error messages".  You need something like the following:

```c#
var connection = new SqlConnection(connectionString)
connection.InfoMessage += Connection_InfoMessage;
```

In your debugging environment ONLY, you may also want to set [https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.fireinfomessageeventonusererrors?view=netframework-4.8](SqlConnection.FireInfoMessageEventOnUserErrors)

```c#
connection.FireInfoMessageEventOnUserErrors = true;
```

The fundamental problem with SQL Server is that, although it has a transactional DDL, when you create nested transactions, it will not stop the nested transaction until _all_ the transactions have been evaluated.  It will THEN rollback.

The final wrinkle in this is that it's somewhat surprising what causes a User Error Message event to fire.  For example, although SQL Server has a Transactional DDL, the handling of "Invalid column 'MyColumn'" message is not the way you would expect.  The main way I learned about these issues is that these issues are the same inconsistency problems that plague SQL Server Transactional Replication; I have provided a script online for computing the transitive closure of dependencies before and after a series of migrations, based on work done by a Microsoft engineer "Karthik PK" (operator of mssqlwiki.com): https://mssqlwiki.com/2012/05/04/copy-database-wizard-or-replication-setup-might-fail-due-to-broken-dependency/

**Comment by jzabroski** [comment]
What you should take away is that the event causing a zombied transaction can happen VERY far away from the actual zombied transaction.

Unfortunately, there is no perfect solution to this problem.

I actually don't even use my own Compute Transitive Closure script; I just verify using Redgate SQL Toolbelt's Find Invalid Objects database right-click menu feature.  If the verification fails, I now use Red Gate SQL CLone to reset the database and fix the bad migration.

![image](https://user-images.githubusercontent.com/447485/67789361-3b3eb500-fa4a-11e9-9c35-281f656ac9df.png)

**Comment by LadyKiller1025** [comment]
What is the solution?
