### ISSUE TITLE
ASP.NET 5 / .NET 4.6 Version ?

### ISSUE THREAD

**Issue by brent-russell** [fluentmigrator/fluentmigrator#621]
Is anyone working on a version targeted for the new .NET frameworks?

**Comment by tommarien** [comment]
@brent-russell Not that i am aware of. Are you volunteering ? :P

**Comment by giggio** [comment]
I am: https://github.com/giggio/FluentMigrator.Runner.Aspnet
There are issues to work around (I just opened a bug here regarding semver #623) and on dnx. But it works.
I am updating it to dnx 1.0.0-beta5 at this moment.

**Comment by ALMMa** [comment]
@giggio, so far I've been using old FM & FM.Runner (not the Aspnet release) under aspnet (full stack, not core) with MSSQL 2012 and 2014. No issues so far.

Missing core clr support though :(

**Comment by giggio** [comment]
We won't get coreclr support until the main fluentmigrator project focuses on it. And System.Data is not in coreclr up until now, so I am not sure if we ever will.

**Comment by brent-russell** [comment]
I like the runner integration.

I saw this https://www.nuget.org/packages/FluentMigrator.ASPNET5Temp/ in @giggio 's source code. Is this just something whipped up to get the Runner project going, or is it an official work in progress of FluentMigrator?

It looks like that package still targets .NET Framework version 4.5.1, and not .NET 4.6. I ran into some compatibility issues trying it out in my test project.

**Comment by giggio** [comment]
@brent-russell This temp package is just a quickfix to get it to work until #623 fix is published. It will be deleted as soon as the new FluentMigrator version is out with the fix. It is the exact same package but respecting semver.

**Comment by dmirmilshteyn** [comment]
Bumping this because I'd like to see some CoreCLR support. 

They've since added System.Data.Common to CoreFX which contains the primitives used from System.Data. Using that, I was able to create a (very experimental, messy) version of the main FM project which targets dnxcore50: https://github.com/dmirmilshteyn/fluentmigrator.

It was fairly straightforward, no really major changes needed. The main changes are:
* IDbConnection -> DbConnection
* ICloneable is not available, but can be manually included when building on dnxcore (it exposes only a single method)
* System.Data.Rule is not available, but that's a 4-item enum which can also be manually included
* ExtensionsForICustomAttributeProvider needs heavy conditional compile blocks, due to type system changes and a lack of ICustomAttributeProvider on dnxcore
* A few small tweaks (eg. Environment.CurrentDirectory -> System.IO.Directory.GetCurrentDirectory())
* Strong name signing needs to be disabled on all projects, otherwise the runner can't load the assemblies
* System.Data.DataSet isn't included on dnxcore, and based on discussions on the CoreFX repo, it seems to be considered legacy. I don't think it's going to be included in it's current form anytime soon. This will likely block the runner form working on CoreCLR for now, but the main FM project can still be ported by removing all references to DataSet. There's only one usage of that, and it appears to essentially be a base class that the runner uses. I've replaced that with an empty IDataSet and created a DataSetContainer in the runner that implements this interface and stores the real DataSet. Then cast from IDataSet to DataSetContainer to get the real DataSet back.

I ran a basic test with an ASP.NET 5 Console Application (targeting dnxcore50) and a Postgres migration and everything worked fine. Not all that extensive, but... it's a start. Is there interest in continuing on? If so, what should the next steps be to start getting this merged into the main repo?

**Comment by fubar-coder** [comment]
We should think about starting to support .NET Core as soon as RC2 is out and supported by VS 2015. With the change to a `project.json`, we're still able to target platforms like .NET 3.5/4 in addition to netstandard1.3 (or higher?).

- [Writing Libraries with Cross Platform Tools](http://dotnet.github.io/docs/libraries/libraries-with-cli.html)
- [.NET Core project system](https://github.com/dotnet/core-docs/blob/master/docs/project-model/index.md)
- [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)
- [Target frameworks](https://docs.nuget.org/Create/TargetFrameworks)
- What is [netstandardapp](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-standard-applications.md)?

**Comment by fubar-coder** [comment]
Progress for conversion is tracked in #712

**Comment by fubar-coder** [comment]
.NET 4.5 (and alike) support is implemented by release/2.0.0
