### ISSUE TITLE
Cannot create a schema through the FluentMigrator method

### ISSUE THREAD

**Issue by blacksagres** [fluentmigrator/fluentmigrator#702]
Hey there,

I was testing the fluent migrator and was unable to create a schema when using the `Create.Schema("test_db");` method. I was only able to overcome that when actually pointing a script to be executed.

Is that a known issue?

**Comment by zendever** [comment]
Sorry for the delay in answering.

I'm making no assumptions here, but to be clear, your connection string is pointing to an active database on a specified server, and you are trying to a schema within that database, correct?

I know there's a difference in lingo depending on which provider you're using (Oracle vs. SQL Server, etc.), so a little bit of clarification might help determining the right answer for you.

**Comment by eloekset** [comment]
It depends on the provider as zendever says. I'm writing an SQLAnywhere provider, and SQLAnywhere requires that the connection that is used to create the schema has userid equal to the schema to be created. https://github.com/schambers/fluentmigrator/pull/659/commits/20858adb04fba7cf82718cb394df105913522de0

**Comment by blacksagres** [comment]
No problem. Thanks for the reply.

That's correct. My connection string points to an active database on a specified server. Starting from that, I was testing how to create another schema. My goal was to create a separate schema and implement my migration scripts on those.

**Comment by zendever** [comment]
@blacksagres ...So, in MySQL, as I'm sure you're aware, treats SCHEMA and DATABASE as synonymous. So, in theory, creating the schema/database in a migration would be possible as long as, the connecting user has the privilege and the migration is not part of a session that has an active table lock (which might be automatically triggered in a transaction). Have you tried to specify the non-transactional attribute on the migration?

Now, I'll be honest, FluentMigrator CAN do these things, but there has been discussion around the true purpose of migration and which schema/database would "own" the migration. Part of the challenge is that migration has to be tracked somewhere, and typically, if you're migrating a database, then the migration should be tracked on the target schema/database. This gets tricky when spinning up a database because without a VersionInfo table to check against, the migrator wouldn't know whether or not the script was run. To get around this, you can obviously connect to a different schema/database, run the script that creates the database, and then in a different transaction, run the rest of the migration against the actual target, but you can see how this might lead to issues down the road (conceptually) since the migration to create the schema/database will be tracked against another schema/database that really isn't the target.

That being said, I do wonder if there should be a "create if not exists" feature that is run only in the even that the target database doesn't exist...but that would mean finding a way to do a connection without an initial schema/database...it's something to think about, for sure.

I hope this sheds a little light on the issue.

**Comment by marcrocny** [comment]
@blacksagres, would be helpful to understand whether this is really a requirement or just a misunderstanding about the schema-database identity in MySQL.  If the former, please change the title of the issue to reflect that this is a requirement for creating a new _database_ via FM; if the latter, please close the issue.
