### ISSUE TITLE
Specify Fill Factor for an Index

### ISSUE THREAD

**Issue by mraz1337** [fluentmigrator/fluentmigrator#704]
When creating index we need to specify fill factor for an index.
This can be done with Execute.Sql, is there any other way, can you add this option to create index options?

**Comment by jzabroski** [comment]
Just do it this way:

```
ALTER INDEX IX_Name ON SCHEMA.TABLE_NAME  
REBUILD WITH (FILLFACTOR = 80);
```

Please note this is not optimal as it will increase the size of your transaction log in order to rebuild the index, so for very large tables you are probably best off just writing Execute.Sql for the whole CREATE TABLE (likely in the case of a clustered index) and CREATE INDEX statements (for non clustered index).

**Comment by fubar-coder** [comment]
Proposed solution is the correct one - until one creates a DB provider specific extension.
