### ISSUE TITLE
Single Build System

### ISSUE THREAD

**Issue by DustinVenegas** [fluentmigrator/fluentmigrator#738]
I was slowly looking at what it would take to port things to .NET Core. While poking around, I noticed there are three different build systems: NAnt, MSBuild, and Rake/Albacore. 

I would like to consolidate the current build systems into CAKE or FAKE. This would assist with contributions (No Ruby on Windows required) and would simplify the build (one place to look). Are there any hard dissents or opinions?

**Comment by dmirmilshteyn** [comment]
I might be wrong, but I think the NAnt portions just provide support for integrating the migration runner into an existing NAnt workflow. I've been able to build the solution using solely MSBuild. In terms of Rake, the amount of work done in the rakefile seems fairly minimal. It may be simpler to just write sh/ps1 scripts instead of bringing in another build system like CAKE, especially since some of the multi-targetting and NuGet management functions are already part of the .NET Core CLI. 

Either way, I'm definitely in favour of simplifying the build system, regardless of how it ends up being done.

**Comment by DustinVenegas** [comment]
@dmirmilshteyn, I believe you're correct for NAnt. Those files probably just need to be moved to reduce confusion. 

Since this project gets compiled cross-platform I figured some meta-runner would be useful. At the least, those options are still fewer dependencies (-Ruby, already depend on .NET). Thoughts?

**Comment by escarls** [comment]
When I look at it, it seems the Rake script is for building the NuGet package and the MSBuild is used by Travis CI.
Not sure what the NAnt script is used for, except it's called from Build.bat.

**Comment by escarls** [comment]
The NAnt script is used by the TeamCity.

**Comment by escarls** [comment]
I think your idea for a single build system is good.
However, I think that to minimize impact of changing, maybe it would be better to go just MSBuild at the start, and then change it to Cake for the next big version change?

**Comment by fubar-coder** [comment]
Solved in the release/2.0.0 branch by using the .NET Core tooling/msbuild
