### ISSUE TITLE
check if there are migrations to run

### ISSUE THREAD

**Issue by feliara8** [fluentmigrator/fluentmigrator#741]
Hi, i have this problem:

I need to know if an assembly has migrations to run, i supposed the validateversionorder task does that job, but i have an assembly that has migrations to run, and shows me valid order.

One solution would be run migrate with -p, and if it has sqls calls then it has migrations to run, but that solution is quirky, is there a better way to do this?

Thank you

**Comment by eloekset** [comment]
I've made something like this in PR https://github.com/schambers/fluentmigrator/pull/701
It's planned for the 1.7 release.

I need it, because in my application migrations are automatically applied using a custom runner, and I want to run a backup of the database if, and only if, migrations are going to be applied.

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
