### ISSUE TITLE
Postgresql: support schema "discovery" via seach path

### ISSUE THREAD

**Issue by richarddbarnett** [fluentmigrator/fluentmigrator#771]
Currently
*  [`PostgresGenerator` always qualifies table names et al with a schema](https://github.com/schambers/fluentmigrator/blob/1.6.2/src/FluentMigrator.Runner/Generators/Postgres/PostgresGenerator.cs#L43).
* If the migration expression doesn't explicitly specify a schema name via `.InSchema`, `.WithSchema`, etc then [`public` is used](https://github.com/schambers/fluentmigrator/blob/1.6.2/src/FluentMigrator.Runner/Generators/Postgres/PostgresQuoter.cs#L10-L15)

This bypasses [`search_path`](https://www.postgresql.org/docs/8.1/static/ddl-schemas.html#DDL-SCHEMAS-PATH) (eg when set in the [Npgsql connection string](http://www.npgsql.org/doc/connection-string-parameters.html)) & so doesn't allow schema to be set in config rather than code.

Support a configuration option, off by default, which when on affects handling of migration expressions without an explicit schema as follows:
* Existence tests in `PostgresProcessor` query all schemas in `search_path`
* SQL generation in `PostgresGenerator` doesn't qualify names with a schema

My use-case for this: 
* I have 15 existing services using FluentMigrator & Postgres, with a database for each service
* I want to migrate the data into a single database with a schema for each service
* I'd like to do this by setting `search_path` for each service, avoiding per-service code changes

**Comment by richarddbarnett** [comment]
Will look at making some of these changes in a fork. The main challenge looks like making the migration expression available when performing the existence tests.

**Comment by fubar-coder** [comment]
You can now specify the default schema name as implemented in the release/2.0.0 branch.

**Comment by richarddbarnett** [comment]
Thanks, this will be useful - once we move to .NET Core ;-/

**Comment by fubar-coder** [comment]
2.0.0 can also be used with the .NET Framework. We're not sure about the min. version, but 4.6.1 will be definitely supported.

**Comment by richarddbarnett** [comment]
Cool, will give it a try.

**Comment by javastud** [comment]
Could someone give a sample for this feature. I read many issues related here but there is no sample. How can "You can now specify the default schema name as implemented in the release/2.0.0 branch." be implemented?

Im using migrations as : 
private static IServiceProvider CreateServices(string connStr)
        {
            return new ServiceCollection()
                // Add common FluentMigrator services
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    // Add Postgres support to FluentMigrator
                    .AddPostgres()
                    // Set the connection string
                    .WithGlobalConnectionString(connStr)
                    // Define the assembly containing the migrations
                    .ScanIn(System.Reflection.Assembly.GetExecutingAssembly()).For.Migrations())
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                // Build the service provider
                .BuildServiceProvider(false);
        }

**Comment by fubar-coder** [comment]
Instantiate a new convention set:

```csharp
var conventionSet = new DefaultConventionSet(defaultSchemaName, null);
```

Append it to your services (after the `AddFluentMigratorCore`):

```csharp
services.AddSingleton<IConventionSet>(conventionSet);
```

**Comment by javastud** [comment]
Thank you. I will try it.

**Comment by i-sinister** [comment]
Why is this issue closed? Problem still exists in 3.2.1 - schema name explicitly specified in migrations is still used. This prevents running migrations at multiple schemas based on the connection string and server configuration. There are several scenarios for this like 'multiple instance for QA for different versions of app' or 'using separate schemas for different customers', to name few.

With postgres one would setup server with user and schemas, assign permissions and setup default schemas for users. Then 'appropriate' schema would be picked based on the connection string and/or [search_path](https://www.postgresql.org/docs/12/ddl-schemas.html#DDL-SCHEMAS-PATH):
```sql
CREATE SCHEMA my_app;
CREATE USER my_app_user WITH PASSWORD '...';
ALTER SCHEMA my_app OWNER TO my_app_user;
ALTER ROLE my_app_user SET search_path = my_app;
```
Now if I dont specify schema name, postgres will use my_app.

Current state of affairs is that "public" is used if  schema name is not specified in migrations explicitly. I could solve it by overriding [PostgresQuoter.QuoteSchemaName](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Generators/Postgres/PostgresQuoter.cs#L64-L68) just to find out that sequential execution of migrator tries to created tables again because [PostgresProcessor](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L84-87) [does](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L89-92) [it](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L94-97) [all](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L99-102) [wrong](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L104-107) when reading metadata by using explicitly specified schema name and not handing "empty schema" cases. Instead, `current_schema()` should be used when schema not specified , like this:
```sql
select * from information_schema.tables where table_schema = current_schema() and table_name = 'my_table'
```
Had to overwrite them all to find another place where "public" is "hardcoded" - this time it was when reading applied versions from migrations table. 

It is possible to solve this problem another way - by connecting to DB, reading `current_schema()` and updating migrations with the returned value, of course, but this is not a constraint imposed by postgres or ado.net driver or anything else, just arbitrary "smart" decision in the fluent migrator. If `'public' schema should be used if not specified` kind of behavior is necessary this should be implemented as "postgres specific options" because other vendors dont have this "public" stuff.

PS: [PosgressProcessor also instantiates PostgressQuoter](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L54) which makes it impossible to override it in the container.

**Comment by jzabroski** [comment]
> Why is this issue closed? Problem still exists in 3.2.1 - schema name explicitly specified in migrations is still used.
> 
> -- @i-sinister

The workaround was described.  Basically, the issue is solved but not integrated directly into the main product, because scraping the connection string for search_path and any other connection-specific things is probably best left as a customization by the user.

> This bypasses [`search_path`](https://www.postgresql.org/docs/8.1/static/ddl-schemas.html#DDL-SCHEMAS-PATH) (eg when set in the [Npgsql connection string](http://www.npgsql.org/doc/connection-string-parameters.html))
>
> -- @richarddbarnett

The search_path is for SQL you wrote; it was never intended to be respected by automatic SQL scaffolding tools like FluentMigrator.  If you want it to work that way, you can do the customization Mark suggested.

> Instead, `current_schema()` should be used when schema not specified
> 
> -- @i-sinister

I don't think it should.  If it did, then if you ran the migrations on Postgres and MySQL, you would get different results.  Part of the point is to maintain as much portability of the schema as possible.  You may not _like_ this architectural style, and it might cause you to write more code, but the point is you can customize things to your hearts content.

That said... I wonder if there is an efficient compromise.  What's the underlying reason for not using public?  I think if we can capture the right user story, it makes sense to support that user story as a feature.  But we're not going to just change the logic to  use `current_schema` because someone said that is how it should work.  As an example, MySQL maps schemas to databases, and most MySQL users I've talked to use a schema as a multi-tenancy construct.  This is pretty different from SQL Server, where schemas are used to segregate permissions to database objects.  In SQL Server, for multi-tenancy, people use a Resource Governor and Database Containment concepts, as these ensure tenant resource allocation fairness and tenant isolation, respectively.

> I could solve it by overriding [PostgresQuoter.QuoteSchemaName](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Generators/Postgres/PostgresQuoter.cs#L64-L68) just to find out that sequential execution of migrator tries to created tables again because [PostgresProcessor](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L84-87) [does](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L89-92) [it](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L94-97) [all](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L99-102) [wrong](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L104-107) when reading metadata by using explicitly specified schema name and not handing "empty schema" cases.

First, why are you quoting v3.2.1 when we are on v3.2.8?  Second, please open issues for these matters, as these do appear to be minor, easy to fix bugs.  Mentioning these in a 3 year old closed issue is how things get lost and don't get fixed.

**Comment by i-sinister** [comment]
> The workaround was described.

Issue description tells that generated sql "bypasses search_path" and uses "public" schema name hardcoded in the migrator library and suggested workaround is ... using schema name that is hardcoded in application. How is this "not bypassing search_path"?

> The search_path is for SQL you wrote; it was never intended to be respected by automatic SQL scaffolding tools like FluentMigrator.

search_path is for any sql statement executed by postgres server and there no difference between a scripts generated by migration libraries and a script generated by application from the server point of view. The rule is simple - if schema name is not specified then first one in search_path is used, if schema name is specified - use that schema.

> I don't think it should. If it did, then if you ran the migrations on Postgres and MySQL, you would get different results. 

The results are already different -  [MySqlQuoter](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.MySql/Generators/MySql/MySqlQuoter.cs#L59) does not use "default schema name" trick and lets [server to decide which schema should be used](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.8/src/FluentMigrator.Runner.MySql/Processors/MySql/MySqlProcessor.cs#L67).

> Part of the point is to maintain as much portability of the schema as possible.

I don't see how "portability of the schema" suffers from removing hardcoded schema name. And I don't understand how hardcoding "public" schema name improves portability in the first place.

> You may not like this architectural style, and it might cause you to write more code, but the point is you can customize things to your hearts content.

This is not about "architectural style" but about one single particular decision - to hardcode "public" schema name for postgres. Things would be more customizable without hardcoded schema names. As I wrote in my previous comment I tried to "customize" migrator to remove "public", but I had to go as deep as rewriting [PostgresProcessor](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs) and it was not enough to make it work. "Rewritting library" != "customizing library".

> That said... I wonder if there is an efficient compromise. What's the underlying reason for not using public?

Well, if everybody could use "public" schema then schemas would not exist in the first place but they do exist in every major non-embedded db. I wrote usage scenario [in my previous comment](https://github.com/fluentmigrator/fluentmigrator/issues/771#issuecomment-673303328) - it is about "one server, multiple application instances":
* multiple version of the same application running side by side in different schemas for testing
* multiple app instances for different customers/departments in different schemas

> First, why are you quoting v3.2.1 when we are on v3.2.8?

That is the version currently used in the application I'm working on. I guess it was latest version when it was added to the project. The [same behavior still exists in v. 3.2.8](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.8/src/FluentMigrator.Runner.Postgres/Generators/Postgres/PostgresQuoter.cs#L64-L68), so exact version does not matter.

> Second, please open issues for these matters, as these do appear to be minor, easy to fix bugs. Mentioning these in a 3 year old closed issue is how things get lost and don't get fixed.

I find having several issues about the same problem more confusing. Consider new issue is created and fixed in a way "someone said that is how it should work". Now you have to 2 issues for the same problem with 2 different outcomes. But if issue can not be "re-opened" new issue can be created.

> As an example, MySQL maps schemas to databases, and most MySQL users I've talked to use a schema as a multi-tenancy construct. This is pretty different from SQL Server, where schemas are used to segregate permissions to database objects. In 
SQL Server, for multi-tenancy, people use a Resource Governor and Database Containment concepts, as these ensure tenant resource allocation fairness and tenant isolation, respectively.

MySql, SqlServer, Oracle, Postgress et al might have (very) different concept of schema. But as this issue is about postgres, design decision about schema usages in other vendors are unrelated here.

**Comment by jzabroski** [comment]
> Issue description tells that generated sql "bypasses search_path" and uses "public" schema name hardcoded in the migrator library and suggested workaround is ... using schema name that is hardcoded in application. How is this "not bypassing search_path"?

You can scrape the search_path value from the connection string by creating a lambda that returns an IConnectionStringAccessor.  There's no requirement it has to be hardcoded.  Workarounds can range from simple to more sophisticated.  I think in this case Mark was just trying to explain where the hooks are, without writing all the pseudo-code (because then people expect you to just go implement it and the conversation drags on).  My viewpoint is that if this is a real problem for someone, then it must add a lot of value, enough where they can budget time to go fix it.

> I had to go as deep as rewriting [PostgresProcessor](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs) and it was not enough to make it work. "Rewritting library" != "customizing library".

Are you looking for guidance on how to submit a PR or are you looking to criticize the code?  I'm not clear on what outcome you want here.



> I find having several issues about the same problem more confusing. Consider new issue is created and fixed in a way "someone said that is how it should work". Now you have to 2 issues for the same problem with 2 different outcomes. But if issue can not be "re-opened" new issue can be created.

When an issue is ~3 years old, it's probably best to create a new issue and link back to the old one.  There's a good chance if whoever raised this 3 years old has moved on to other things, and they don't need to be bothered by this discussion.

Separately, in terms of opening multiple issues, when the issue is actually about several things (1. using schema from search_path provided in connection string 2. using current_schema() when none is specified 3. replacing public as deault with `current_schema()` as default 4. rounding up all places where default schema is not customizable and making that customizable) then it is probably best to start with a GitHub discussion and ask what the best approach here is.

In the case of using `current_schema()`, I'm not sure that is actually the right approach.  I don't know how current_schema can change, since I'm not an expert in Postgres, but in SQL Server (for example) values change on `sp_reset_connection` in order to clean connections when they're returned to the connection pool.  From StackOverflow, It looks like you can also [set the search_path dynamically in pgsql](https://stackoverflow.com/questions/34098326/how-to-select-a-schema-in-postgres-when-using-psql):

```sql
SET search_path TO myschema, public;
```

 **so, in theory, one migration might bleed into another migration**, and make it very hard to troubleshoot why one engineers migration impacted anothers.  I believe migrations should be modular entities.  Do you agree?  In this case, **`DEFAULT` is not the same thing as `current_schema()`**.

The other benefit to making smaller issues is they create smaller PRs that can be made more widely available without creating breaking changes for others.  We can have more hyper-focused discussions about what the right approach is.   We all want awesome software powering our delivery lifecycle.

**Comment by jzabroski** [comment]
> The results are already different - [MySqlQuoter](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.MySql/Generators/MySql/MySqlQuoter.cs#L59) does not use "default schema name" trick and lets [server to decide which schema should be used](https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.8/src/FluentMigrator.Runner.MySql/Processors/MySql/MySqlProcessor.cs#L67).

Actually, and this is hard to infer by looking at the code since it looks so similar to Postgres, but the MySqlQuoter is actually equivalent to saying "Use the database name from the connection string as current schema", which is similar to your feature requirement, it's just that the default schema comes from a different part of the connection string.  MySQL `schema()` does something different than Postgres `current_schema()`, because Postgres is closer to how SQL Server works than how MySQL works.

Thanks for bringing this up as I think it helps clarify what the right behavior should be across different processors.  In this case, I think, summing up what we've discussed so far, the real problem is that customizing the Postgres default schema is a bit difficult, since it requires knowledge of Microsoft DI to get a lambda to the `IConnectionStringAccessor`, and then at runtime call that lambda inside a `IPostgresQuoter` in order to get the scraped default schema value.  Even then, it's not 100% clear what the behavior should be when `search_path` contains multiple values.  Perhaps it should throw an exception?  But that might be a breaking change and require a 4.0 release.

**Comment by jzabroski** [comment]
@i-sinister I will implement a way to lock all old discussions with a robot that mentions the proper etiquette.  I think you raised a number of good process points here and made me think more deeply about various project management issues, so thank you.  Hope we can continue this discussion.  I plan to start locking old threads soon with a notice that communicates guidelines on opening new issues.

**Comment by i-sinister** [comment]
> You can scrape the search_path value from the connection string by creating a lambda that returns an IConnectionStringAccessor. 

This would not be necessary in the first place if postgres processor were working like mysqls instead of putting "public" schema everywhere. Also workaround does not work when search_path is not specified in connection string. But, again, mysql implementation does not require any workaround because it does not contain any magic default schema name.

> Are you looking for guidance on how to submit a PR or are you looking to criticize the code? I'm not clear on what outcome you want here.

I'm criticizing design decisions for postgres runner and development practices:
* "unexpected behavior" when running migrations against postgres
* workaround suggested for the problem does not work but issue is closed (I guess workaround was not checked or, maybe, it was broken in later versions)
* fixing what seemed to be a "low hanging fruit" turned into rewriting of the library

Currently there are more critical issues on the project I am working on so I'm not considering submitting PR until its important again.

> Separately, in terms of opening multiple issues, when the issue is actually about several things...

Points 2 and 3 are the same and, IMHO, this is what creator of the issues needed. Yes,  search_path **may be specified** in the connection string and workaround could be allied if worked but it does not because just registering quoter in container is not enough:
* table existence checked in "public" schema
* migrations table itself is created in "public" schema

And if search_path is not in the connection string application needs to open connection to read schema before creating DI container.

> so, in theory, one migration might bleed into another migration

"Every" db supporting schema also supports switching schema via sql statements, including MySql. However, MySqlProcessor is using `SCHEMA()` and it does not prevent migrations from being modular. Also does migrator provide an api to change current schema? If it does not then this is not even concern. If there is an API then I would read it once before running migrations and used if schema is not explicitly specified when reading metadata and would omit schema on table creation at all. This also applies to mysql.

> In this case, DEFAULT is not the same thing as current_schema().

What is `DEFAULT` schema? Why it has to be "public" for postgres? Why migrations should be created in `DEFAULT` schema instead of schema that is user connected to?

>  as the goal is to "do the least surprising thing".

Do you consider creating tables in "public" schema when connecting to "my_app" schema as "least surprising thing"?

> This is similar to how Microsoft DI creates a standard of 50 test cases all DI containers implementing the Microsoft DI interfaces must conform to in order to be a compliant container.

No way these are similar. Whereas DI container interface defines contract all implementations must adhere to there is no contract/agreement between different db vendors about what schema is - every vendor implemented schema for a particular use case and, as you told yourself, schemas in MsSqlServer are very different from schemas in MySql (and even more different from schemas in Oracle). Regarding contract for using schemas and migrations one would expect something like "DB objects are created in whatever schema I am connected to if not specified otherwise".

> Actually, and this is hard to infer by looking at the code since it looks so similar to Postgres

MySqlProcessor uses `SCHEMA()` function that results in using whatever schema is defined in connection string or server configuration and PosgresProcessor uses `quoter.QuoteTableName` and `FormatToSafeSchemaName` that results in using *hardcoded "public" value* as a schema name. How are these "similar"?

> MySQL schema() does something different than Postgres current_schema()

In MySql `SCHEMA()` [is an alias to DATABASE()](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_schema), which [`returns the default (current) database name as a string in the utf8 character set`](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_database). In Postgres `current_schema()` [ `returns the name of the schema that is at the front of the search path (or a null value if the search path is empty). This is the schema that will be used for any tables or other named objects that are created without specifying a target schema`](https://www.postgresql.org/docs/8.3/functions-info.html). I dont see much difference from the DB client's perspective - when schema name is omitted `SCHEMA()`/`current_schema()` result is used.

> You can see this by observing that the MySQL docs for [Setting the Current Schema](https://dev.mysql.com/doc/x-devapi-userguide/en/setting-the-current-schema.html) talk about it at the ODBC driver level

`getCurrentSchema()` is a function in a driver api whereas `SCHEMA()` is server builtin functions. Most probably in the driver schema name is cached when connection is opened. Comparing apples to orages here anyway.

> I think, summing up what we've discussed so far, the real problem is that customizing the Postgres default schema is a bit difficult

First of all, problem is not "customizing default schema" but "using hardcoded value in postgres" - "default schema" for MySql works as expected (which is actually "current schema"). Second - currently it is not difficult but impossible to customize "default schema" without rewriting the most part of postgres runner.

> I Even then, it's not 100% clear what the behavior should be when search_path contains multiple values. Perhaps it should throw an exception?

I would expected `use current schema in not specified explicitly` kind of behavior.

> But that might be a breaking change and require a 4.0 release.

[Feature toggles](https://en.wikipedia.org/wiki/Feature_toggle) for the rescue - there is already [runner options support](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresOptions.cs) so this is just one of them. Of course support for specifying options from the consuming application should be added.

**Comment by jzabroski** [comment]
> This would not be necessary in the first place if postgres processor were working like mysqls instead of putting "public" schema everywhere. Also workaround does not work when search_path is not specified in connection string. But, again, mysql implementation does not require any workaround because it does not contain any magic default schema name.

OK, I re-read our discussion.

1. You're not advocating we support `search_path` from the connection string (which is _what this issue is about_)
2. Instead, you're advocating we we support `current_schema()` instead of `"public"` in the places you mention.

I think the proposed fix then is the following (if you agree and want to do the work to create the PR and write the tests, that would be awesome).

Update PostgresQuoter.QuoteSchemaName: https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Generators/Postgres/PostgresQuoter.cs#L64-L68 to be:

```c#
       public override string QuoteSchemaName(string schemaName)
        {
            if (string.IsNullOrEmpty(schemaName))
                return "current_schema()"; // don't quote pg/sql intrinsic functions
            return base.QuoteSchemaName(schemaName);
        }
```

In terms of the calls in PostgresProcessor "when reading metadata by using explicitly specified schema name and not handing "empty schema" cases." - Unless I am mistaken (I would need to step through the code), the values in the following calls all go through the convention set pipeline, so if no schema is specified, it will use the convention set default schema.  **Is that not the case?**

Assuming I am right (that convention set will supply a default schema), the other task is to:

Update PostgresProcessor so that the belows **calls to `FormatToSafeSchemaName(schemaName)`** check if the schemaName is an intrinsic or not (a _bit hacky_, so **please provide your feedback on whether you think this is acceptable**):

https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L183-L192
```c#
        private string FormatToSafeSchemaName(string schemaName)
        {
            var schemaNameCased = schemaName;
            // First, before applying force quote behavior, check if the schemaName is the PGSQL intrinsic function current_schema()
            // as we don't want to quote intrinsic functions.
            if (string.Equals(schemaNameCased, "current_schema()", StringComparison.OrdinalIgnoreCase)
            {
                return schemaNameCased;
            }
            if (!_quoter.Options.ForceQuote)
            {
                schemaNameCased = schemaName?.ToLowerInvariant();
            }

            return FormatHelper.FormatSqlEscape(_quoter.UnQuoteSchemaName(schemaNameCased));
        }
```

### Calls to `FormatToSafeSchemaName(schemaName)`
1. https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L84-87
2. https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L89-92
3. https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L94-97
4. https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/PostgresProcessor.cs#L99-102
5. https://github.com/fluentmigrator/fluentmigrator/blob/v3.2.1/src/FluentMigrator.Runner.Postgres/Processors/Postgres/Postgresrocessor.cs#L104-107


> [Feature toggles](https://en.wikipedia.org/wiki/Feature_toggle) for the rescue

The problem with feature toggles is they create state space explosion for regression testing.  They're fine if you're developing a product and trying to determine what behaviors users really want, but they over-complicate the code.  In particular, they can create _modus ponens logic errors_ when developers try to _in situ_ update the code, because it is not always clear what it means for a feature to be disabled (when you introduce `featureFlag`, it is not as simple as just saying `!featureFlag`, because you have to prove the contrapositive e.g. via creating a truth table that shows there are no "holes" in your inductive reasoning by forcing you to do static analysis of assertions (e.g. `!q -> !p`)!  A fascinating academic talk about this is called _[No ifs, ands or buts](https://vimeo.com/140738254)_ by Jonathan Edwards).  As an example, somebody long before I started maintaining this project added this concept of `ForceQuote` variable names for Postgres and Firebird, which for my taste is inferior to creating a "Tagless Final" `Identifier` that can be either a quoted identifier or a sql expression that shouldn't be quoted (e.g., an intrinsic function like `current_schema()`).

Anyway, in my experience, the main people pushing feature toggles are companies that sell Real User Monitoring software and want you to buy their software because it can do (gasp!) A-B testing.  I worked in algorithmic trading for awhile, and feature toggles were always considered the solution to every problem, and it created a giant mess where we had over 500,000 test cases but customers still complained about regressions in behavior, in part because of what I just described above.  And everyone was afraid to kill off features and make the problem even worse. And they're not wrong!  At a very large scale, humans cannot even effectively reason about A-B testing due to the computational complexity of Approximate Bayesian computation (ABC) as the feature set grows. And on small graphs, Hadwiger's Conjecture for coloring a graph is true, but it eventually stops working in super large graphs.


Side note: I looked at what EFCore does; it does not use `current_schema()` and instead requires the developer to call [`modelBuilder.HasDefaultSchema(...)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalmodelbuilderextensions.hasdefaultschema?view=efcore-2.1#Microsoft_EntityFrameworkCore_RelationalModelBuilderExtensions_HasDefaultSchema_Microsoft_EntityFrameworkCore_ModelBuilder_System_String_).  As I previously mentioned, it's not clear to me that `current_schema()` is the right default behavior.

**Comment by i-sinister** [comment]
> You're not advocating we support search_path from the connection string (which is what this issue is about)

Here is the essential part of issue description:
> > This bypasses search_path **(eg when set in the Npgsql connection string)** & so doesn't allow schema to be set in config rather than code.
> > 
> > Support a configuration option, off by default, which when on affects handling of migration expressions without an explicit schema as follows:
> >  * Existence tests in PostgresProcessor **query all schemas in search_path**
> >  * SQL generation in **PostgresGenerator doesn't qualify names with a schema**

So lets take it line by line:
1. it tell `**...eg when set in ... connection string**` - so this is just an example of how search_path can be configured but if search_path is not configured in connection string it does not mean it is not defined and should not be handled. Put it another way - search_path is always defined for the session even if it not specified in the connection string. Usually search_path is configured by DBA and connection string contains user and database names.
2. it tells `query all schemas in search_path` which is not the same as `take first schema from the search_path in connection string and put it everywhere`
3. it tells `PostgresGenerator doesn't qualify names with a schema` which is not the same as `use default schema when creating tables`, it explicitly asks for schema name to be omitted.

In total this issue is not about `support search_path from the connection string`but about generating migrations that work correctly with Postgres respecting its approach to schema handling. By the way issue also asks for a feature toggle.

Once again - suggested workaround does not work - on initial run tables are created in the "correct" schema (except migrations table), but sequential executions fail because they try to create tables again because they read metadata from the wrong schema.

> The problem with feature toggles is they create state space explosion for regression testing

Feature toggle is a way to solve a specific problem - modyfing application behavior without recompilation. If you dont have such a problem (eg do not have to support two ways migrations for postgres are generated) then you dont have to have feature toggles, but if you do then its better to have tests with feature enabled and disabled. If there are 2 independent features protected by toggles there should be 4 tests. I dont see a problem here. Not every feature should be protected by toggle and sometimes features are actually bugs and it is better change the behavior as soon as it is discovered without feature toggle.

Current behavior works for some users of migrator library that are lucky enough to hardcode schema names in their app and demand new hardware/vm and postgres server installation for new instance of their app. So to avoid breaking changes feature toggles are the way to go.

Alternatively new runner/generator for postgres that implements this feature request can be added and client will be left to choose which suits them.

**Comment by jzabroski** [comment]
Can you comment on whether the fix I outlined solves your problem? It sounds like you want it to add a feature toggle, but otherwise you have not weighed in on it?

**Comment by i-sinister** [comment]
> Can you comment on whether the fix I outlined solves your problem? It sounds like you want it to add a feature toggle, but otherwise you have not weighed in on it?

No, this fix will make generated queries look like `CREATE TABLE current_schema()."MY_APP_TABLE_NAME" ...` which is not a valid sql.

**Comment by jzabroski** [comment]
@i-sinister Any thoughts on the last two replies?  Understand you're probably busy hitting a deadline.  I put together the above in part to help you.

**Comment by jzabroski** [comment]
@i-sinister I moved the above table and footnotes to: https://github.com/fluentmigrator/fluentmigrator/blob/master/adr/proposed/DefaultSchema.md
