### ISSUE TITLE
Documentation contribution workflow

### ISSUE THREAD

**Issue by marcrocny** [fluentmigrator/fluentmigrator#785]
I see (#697) that the project has been going through some leadership changes at the moment.  I'd like to add some documentation around Maintenance migrations, but not sure if there's a process to this--in a sense, it's almost easier to add to the code (via PR).  Can anyone just edit?  (Is this more of a general Github question?)  If so, after editing, is there anything we need to do trigger a review?

**Comment by fubar-coder** [comment]
The Wiki itself allows documentation changes by everyone and we don't plan to change it. When you want to do some major changes to the Wiki, then please add an issue first where we're able to discuss the changes.

What I'd consider as major:

* Complete rewrite of a single page where the old page was more than a simple placeholder (e.g. a new "getting started" page)
* Changes to the main page that also change the main "structure" of the Wiki
* Changes to pages whose content you don't agree with (i.e. represents an opinion, not an error)

What I'd consider as minor:

* Adding a link or a small explanatory paragraph to the main page
* Adding/modifying/replacing a single paragraph
* Minor modifications to multiple paragraphs

What I'd always welcome (without the need to issue a ticket first):

* New documentation (new page)
* Addition of examples
* Clarifications to existing documentation

**Comment by reinaldocoelho** [comment]
@fubar-coder It looks to me a great thing. Can you create a Git Pages?

I make the change of documentation to new location.

Suggestion: I think use the "/docs" folder is better to register the pages, what you think?

**Comment by marcrocny** [comment]
Seems to me that this would add formality that solves the workflow question out-of-hand.  If @fubar-coder is happy with it, I'm all for it.  Thanks!

**Comment by fubar-coder** [comment]
@reinaldocoelho Yes, `/docs` is a good place. BTW: You can clone the Wiki from [here](https://github.com/fluentmigrator/fluentmigrator.wiki.git).

@tommarien @schambers Maybe the FluentMigrator documentation changes are interesting for you?

I'm definitely willing to accept this change, but it's not just a matter of moving the wiki to the new place:

* [GitHub Pages doesn't support textile files any more](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)

   Some of the Wiki pages are still in textile format and need to be converted.

* GitHub Pages ([Jekyll](https://jekyllrb.com/)) doesn't support a sidebar by default

Those problems mean, that it's not an easy 5-minute task, because to support a sidebar, we definitely have to use use some HTML.

# Sidebar

We can use folloing solutions:

* Don't use a sidebar
* Use a documentation tool (like e.g. [Sphinx](http://www.sphinx-doc.org/en/stable/) or [docfx](https://dotnet.github.io/docfx/))

The "no sidebar" solution would work, but it would be not that usable. The "documentation tool" solution will work, but all tools have different drawbacks.

# Documentation tool

* [Sphinx](http://www.sphinx-doc.org/en/stable/)

  **Pro**:

    * We would be able to use [readthedocs](http://docs.readthedocs.io/en/latest/) and the default template looks very good.
    * It's a commonly used and stable tool

  **Con**:

    * We have to write the API documentation ourself
* [docfx](https://dotnet.github.io/docfx/)

  **Pro**:

    * It can provide API documentation
    * The default template OK, but not as nice as the one from readthedocs. [Example](https://fubardevelopment.github.io/WebDavServer/)

  **Con**:

    * No support for .NET Core yet (see issues dotnet/docfx#1028, and dotnet/docfx#1254), but it seems that there is a workaround mentioned (not tested though)

Some things to consider:

* We don't provide an API documentation yet
* We want to switch to .NET Core sooner than later

# Textile

The textile files have to be converted to markdown to be usable by GitHub Pages.

# Goals

* Be able to accept pull requests for the documentation
* Achieve the transition with minimal effort

# Possible solutions

* Use [Sphinx](http://www.sphinx-doc.org/en/stable/)
  * Host the documentation on [readthedocs](http://docs.readthedocs.io/en/latest/)
  * Use a tool to create the API documentation as [rst](http://docutils.sourceforge.net/rst.html) from xmldoc or just don't create the API documentation or host it externally ([just like AutoFac does](http://autofac.readthedocs.io/en/latest/))
* Use [docfx](https://dotnet.github.io/docfx/)
  * Host the documentation using GitHub pages
  * Use the template from the [example](https://fubardevelopment.github.io/WebDavServer/)
  * Add the API documentation (when possible)
* Use GitHub pages without a tool
  * No (searchable) sidebar
  * I don't know if all Jekyll features are available (Test with a date: {{ site.time | date_to_long_string }})
  * Everything done by a template (header, footer, etc) has to be manually included into every document

I'd propose one of the first two solutions with a slight bias towards docfx.

The conversion from textile to markdown has to be done anyways. The markdown files allow us to switch between the two documentation tools quickly.

**Comment by fubar-coder** [comment]
Solved by creation of a [documentation repository](https://github.com/fluentmigrator/documentation).
