### ISSUE TITLE
FluentMigrator.Runner explicitly depends on all database specific packages?

### ISSUE THREAD

**Issue by JosephRT** [fluentmigrator/fluentmigrator#847]
Just upgraded to 2.0 and noticed that there are a large number of new packages,  It seems that the vast majority of the runners for specific DBs.  Out of curiosity, is there any plans to decouple the Runner and Core from all of the specific runners?  It's not that big of an issue, but I personally like to keep my dependencies as clean as I can and only reference the specific runners that I need.

**Comment by fubar-coder** [comment]
Yes, it's planned, but we're not there yet. The main problem is `MigrationRunner` and all its dependencies. All those dependencies will (hopefully) be broken up with release 3.0 by making heavy use of dependency injection.

You can use the existing infrastructure to implement your own runner. Your main task would be:

1. Implement your own IAnnouncer (simple)
2. Implement your migration version management (medium difficulty)
3. Implement your own runner
   - Find the migrations (quite easy when using [Scrutor](https://github.com/khellang/Scrutor))
   - Implement your own `IMigrationContext` (simple)
   - Get the expressions by calling `IMigration.GetUpExpressions` (simple)
   - Apply the expression conventions (you can find an example implementation iun `DefaultConventionSet`) (simple)
   - Execute migration expression inside a transaction (simple, just use the processor for the target database)

As you can see, the most difficult part is the version management. One of the goals in 3.0 is to simplify the implementation of your own runners, but currently its dependencies are difficult to untangle.

I close this issue, because I guess that your question is answered 😄

**Comment by JosephRT** [comment]
Yup yup, that covers it.  😄 Thanks for the info!
