### ISSUE TITLE
Using the IDENTITY Firebird 3.0 column

### ISSUE THREAD

**Issue by eduprog** [fluentmigrator/fluentmigrator#861]
I've tried every way, generate the `ID` column as `IDENTITY `in Firebird, now that Firebird 3.0 has this possibility, I would like to know what we can do so we can use this feature, because until version 2.5 we had to create a` generator` and a `trigger`. Until version 2.5 I created via `SQL` command the `Triggers` and `Generators`.

Once created through _IBEXPERT_ your `DDL` looks like this:
```
CREATE TABLE PERSONTEST (
    ID            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME      VARCHAR(150),
    CREATEDATE  DATE NOT NULL
);
```

I believe the correct one would be to create a factory:
 `Firebird3ProcessorFactory processorFactory = new Firebird3ProcessorFactory ();`

implementing identity in this class.

**Comment by fubar-coder** [comment]
That is correct. The current Firebird 3 support fixes only the problem with default null constraints and doesn't implement other features. You may try to implement a Firebird3Generator that I'll gladly add for the next release. Don't be surprised when you PR wont get merged in the traditional way, because the `develop` branch contains some quite heavy changes to the infrastructure.

**Comment by eduprog** [comment]
Honestly, I'm kind of lost to make a deal in class. You can explore things and just as you like, using the field that checks if `Firebird 3.0` is handling nulls, so I'll add the identity to be generated. This will simplify a lot, so you do not have to create `generators` and `triggres`. Because this way is much more laborious.
Thank you for now.
