### ISSUE TITLE
Run-time connection string updates

### ISSUE THREAD

**Issue by newanalog** [fluentmigrator/fluentmigrator#882]
Is it possible in v3 to update the connection string at run-time? I am trying to iterate over several databases with different connection strings and apply the same migrations from a .dll to each database.  I want to omit the `.WithGlobalConnectionString` runner builder extension (this won't be necessarily known at startup) and just set the connection string in a loop.

My service provider is created like this:
```cs
static IServiceProvider CreateServices()
{
    return new ServiceCollection()
        .AddFluentMigratorCore()
        .ConfigureRunner(rb => rb
            .AddSqlServer()
            .WithMigrationsIn(typeof(SomeMigrationClass).Assembly))
        .AddLogging(lb => lb.AddFluentMigratorConsole())
        .BuildServiceProvider(false);
}
```

I am getting at the `ProcessorOptions` and attempting to set the connection string like this in my loop:

```cs
var migrationRunner = _serviceProvider.GetRequiredService<IMigrationRunner>();
var processorOptions = _serviceProvider.GetRequiredService<IOptionsSnapshot<ProcessorOptions>>().Value;

processorOptions.ConnectionString = "MYCONNECTIONSTRING";

migrationRunner.MigrateUp();
```
When I do this, the `migrationRunner.Processor.ConnectionString` is never changed.  It uses the default "No Connection".  Am I doing something wrong?

**Comment by newanalog** [comment]
Number 2 sounds like the way I would go, but any `IConnectionStringReader` resolved from the container will not have the settable `ConnectionString` property that my implementation class has.  If I cast to my implementation class, I can set my `ConnectionString` property, but it still does not update the `ConnectionString` property on `MigrationRunner.Processor`.

**Comment by derekgreer** [comment]
I wouldn't recommend any approach involving changing state (e.g. using a writable ConnectionString property).   This introduces issues with concurrency which you could solve, but the fact that you have to think about it is a design smell.  A better approach would be to have a migrator factory which allows you to pass in the connection string.

**Comment by derekgreer** [comment]
Perhaps it would be better to pose the desired solution and then ask whether fluent migrator currently supports it.

Here's what I'd say you want to do:

```
foreach(var client in clients)
{
    var migrator = _migratorFactory.CreateMigrator(client.ConnectionString);
    migrator.MigrateUp();
}
```

**Comment by newanalog** [comment]
I was able to get this to work using your second suggestion.  Order that the services are resolved in matters.  This **does not** work:
```cs
var migrationRunner = _serviceProvider.GetRequiredService<IMigrationRunner>();
var connectionReader = _serviceProvider.GetRequiredService<IConnectionStringReader>();

((MyConnectionStringReader)connectionReader).ConnectionString = connectionString;

migrationRunner.MigrateUp();
```
This **does** work:
```cs
var connectionReader = _serviceProvider.GetRequiredService<IConnectionStringReader>();
((MyConnectionStringReader)connectionReader).ConnectionString = connectionString;

var migrationRunner = _serviceProvider.GetRequiredService<IMigrationRunner>();

migrationRunner.MigrateUp();
```
I would like to know your thoughts on @derekgreer's comment though.

**Comment by fubar-coder** [comment]
@newanalog I provided two examples to show you how to achieve your desired behavior: https://github.com/fluentmigrator/fluentmigrator/blob/master/test/FluentMigrator.Tests/Unit/IssueTests.cs

* `Issue882WithCustomConfigReader` shows how to change the connection string globally (your code was already almost correct)
* `Issue882WithAutofac` changes the connection string only for the given scope, but requires the usage of [autofac](https://github.com/autofac/Autofac) under the hood.

Regarding @derekgreer's comment:

Use solution 1 when you can ensure that the connection string only changes once and you don't have concurrent accesses.

Use solution 2 when you may have concurrency problems. This may happen when you're developing a service that has to be able to upgrade different databases concurrently.

I'm a little bit on the pragmatic side and I'd use solution 1 in most cases, because sometimes you just have a global state - and the selected database/configuration is very often one of them.

**Comment by fubar-coder** [comment]
Please close this issue if your question is answered.

**Comment by newanalog** [comment]
Sure.  Thanks @fubar-coder.

**Comment by nZeus** [comment]
Hi.

I have the same problem, but I wonder if a different solution can be implemented?

>1. Create a new service collection/provider for your migrator when you need it.

This works, but it ends up as an ugly workaround, as many services need to be re-registered.

> 2. Creating your own IConnectionStringReader implementation and adding at as singleton. Just like a PassThroughConnectionStringReader, but with a writeable connection string property.

This doesn't work if you get the connection string after the service provider has been built.

> 3. Installing FluentMigrator 3.1.0-beta.5 from this MyGet feed and use a configuration provider that supports change detection (e.g. JSON files).

I couldn't find any documentation for this one. Could you please share some links?

---

Ideally, it should be possible to set the connection string right before the migrations start. E.g.:

```cs
migrationRunner.SetConnectionString(__MyConnectionString__);
migrationRunner.MigrateUp();
```

I believe the `SetConnectionString` extension method would allow us to not have any workarounds with DI/Readers/etc. 
Can it be added, please?

**Comment by fubar-coder** [comment]
@nZeus As a migration is something that you should only do at the start of your services, why don't you just create your own service collection just for the migration services?

I don't think that there is a need to have long-lived services with changing connection strings.

BTW: Adding `SetConnectionString` to the migration runner will most likely never happen. As I wrote, you can always create your own service collection and just set the connection string with a `.WithGlobalConnectionString(connectionString)` in the `ConfigureRunner` extension method.

**Comment by jzabroski** [comment]
I agree, it does not make sense to change a connection string for things that might have disposable object graphs related to that connection.  It's too clever by half to try to just update the connection string and assume nobody has some static state somewhere that could leak across connection strings.

Just create unique service collections and key them with what you want to do.  There is no free lunch - you have to model your problem.

**Comment by nZeus** [comment]
> _why don't you just create your own service collection just for the migration services?_

This is what I did in the end, but a deferred setting of the connection string would simplify it.

Well, I think you're right, in the end. Even though it would be _convenient_ to have such a feature, it's not the root cause of the problem. And even if there would be a mechanism to set the connection string after it's added to the service collection, we would then need to have a way to re-initialize the whole runner (e.g. also to set the db-engine and the rest of the extensions).

> _it does not make sense to change a connection string for things that might have disposable object graphs related to that connection_

The topic is not about changing the connection string back and forth, but about the possibility to defer the setting of the connection string (:= set it when ready to run the migration).

**Comment by jzabroski** [comment]
Thinking about this. It is a known problem that Microsoft DI does not allow ambient contexts. You can't `Func<Runner> Runner {get;set;}`. Instead you need to create a meta interface that returns an enumeration of runners each configured differently. 

If you happen to think of a different approach I would like to learn it.

**Comment by nZeus** [comment]
No, I don't, I ended up implementing the first approach.

Thank you guys for the help and thoughts.
