### ISSUE TITLE
Question: Are there plans to support also NoSQL databases

### ISSUE THREAD

**Issue by cmenzi** [fluentmigrator/fluentmigrator#906]
Hi

I basically used fluentmigrator alot for relational database systems. But as time goes, there are also databases like MongoDB, CosmosDB, DocumentDB or for example columnstore based like Cassandra, ... , where we have schema-less databases, but content of those documents may have to be migrated. So, the schema is more or less inside the database.

Could you imagine that fluentmigrator also support such databases, where the migration does more or less just process existing documents to a target schema?

**Comment by fubar-coder** [comment]
What you wrote about seems like a data migration tool, which is out of the scope of this project.

**Comment by pjmagee** [comment]
We use migrations for mongodb in order to rename collections, manipulate indexes etc through an up and down mechanism, sometimes that can include data migration but not always. It's a document store, not a SQL store, that doesnt mean it cant be considered migration. Migrations should include anything that is migrating... and if that means sometimes it's data, why not - if it makes sense for that technology?

FluentMigrator would seem like a good project in order to support nosql and run migrations like indexes, creating collections, renaming them, removing them etc.

**Comment by jzabroski** [comment]
This question comes up every now and again.  In short, nobody is planning to do anything here.  It could be of interest, but it might also be difficult to fit into the existing framework.
