### ISSUE TITLE
Updating Microsoft.Extensions.* packages break FluentMigrator.MsBuild task.

### ISSUE THREAD

**Issue by schh** [fluentmigrator/fluentmigrator#914]
After updating all the Microsoft.Extension packages to the latest versions (2.1.1) i get the following when running migrations with the MsBuild task:

error : While executing migrations the following error was encountered: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.,    at FluentMigrator.MSBuild.Migrate.ExecuteMigrations() 

It works fine before update, and i know that the updated assembly is available. The current version of Microsoft.Extensions.DependencyInjection.Abstractions is 2.1.1

Migrations in code works fine with the latest version installed.

**Comment by fubar-coder** [comment]
There is nothing I can do here without updating the FM MSBuild task for every M.E.* package version change, which is a futile effort. The solution would be one of the following:

- use assembly redirects, which is difficult, because one had to change the msbuild.exe.config
- use the `dotnet-fm` tool
- put the migrations in a separate assembly and only use the "old" package for this migrations project while using the latest packages on all other assemblies
- use the new `PackageReference` instead of the `packages.config` and let the build system pull the packages indirectly (via the FluentMigrator package references) while using the latest packages on all other assemblies

**Comment by schh** [comment]
Thank you very much for the PackageReference suggestion. I should probably have done that for a long time. Now i finally got it done.
