### ISSUE TITLE
Any way to insert data outside of a migration?

### ISSUE THREAD

**Issue by Elycin** [fluentmigrator/fluentmigrator#917]
Hi There,
FluentMigratior is an awesome library I'm beginning to make use of - this issue is more of an inquiry instead of a direct problem with this repository.

I've looked at the documentation and fiddled with a few namespaces but can't seem to get a crack at it.
The way the project is structured where i'm working is through services and sub-libraries being injected through reflection into a `IServiceCollection` for ASP.NET. Is there any way I can call functions such as `Insert.IntoTable()` through another service?

Regards,
Andrew

**Comment by fubar-coder** [comment]
That's only supported from within a context of a running migration, but you can use your services from within the migration and are therefore able to pass the migration to your service even though it's not advisable. Be aware that the `Insert.IntoTable()` and similar functions aren't directly executed. Instead they are just collected and executed in a batch afterwards.

In case I misunderstood your question, you can always use libraries like - for example - [Dapper](https://github.com/StackExchange/Dapper), [EntityFramework Core](https://github.com/aspnet/EntityFrameworkCore), [NHibernate](https://github.com/nhibernate/nhibernate-core/) or other projects from a migration without a transaction (configurable via `Migration` attribute parameter) and using `Execute.WithConnection` while ignoring the transaction (because it'll be likely handled by the O/R-Mapper of your choice).
