### ISSUE TITLE
Infinite loop when incorrect assembly is passed to console runner

### ISSUE THREAD

**Issue by havranek1024** [fluentmigrator/fluentmigrator#970]
When I pass incorrect assembly path to FluentMigrator.Console tool, it outputs the error "!!! Failed to load assembly with name (...)". However, it does so in an infinite loop, with increasing nesting level for each error. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/6151833/49783722-0be06600-fd1b-11e8-8a90-c0c701201020.png)

**Comment by Lopopix** [comment]
I also had this problem...

After some look and debug in the code, I that there was a recursive call in  LoggingUtilities class : 

![FluentMigrator-ConsoleRunner](https://user-images.githubusercontent.com/32832333/74323818-62fe2280-4d86-11ea-8cef-3de4b9c8c1c6.JPG)

Should it not be : 
`writer.WriteExceptionMessage(innerException.Message, level)` ?

**Comment by jzabroski** [comment]
I think you're right. Will fix today

**Comment by PeterKneale** [comment]
@vgrigoriu i dont believe this was fixed, added tests to reproduce it jere:
https://github.com/PeterKneale/fluentmigrator/commit/903bbde856ee7363b608c574762414439878060c

**Comment by jzabroski** [comment]
Yes, it was not fixed.  Thanks for the tests!

**Comment by jzabroski** [comment]
@PeterKneale I fixed the tests and also `Flatten()`ed the `AggregateException` so that the "true" issue gets displayed.  Your test doesn't directly cover this (but came close in `Write_aggregate_exception_of_two_exceptions_each_with_inner_exceptions_one_of_which_is_an_aggregate`) but if you'd like to further improve it, you can.
