### ISSUE TITLE
Question: How to use fluentmigrator in ASPNet Core runtime only linux container

### ISSUE THREAD

**Issue by bhavyamathur** [fluentmigrator/fluentmigrator#975]

**Comment by bhavyamathur** [comment]
> TBH: I don't have an idea. I just use `dotnet publish` and copy the output to my server. Maybe this link can help you: https://docs.docker.com/engine/examples/dotnetcore/#create-a-dockerfile-for-an-aspnet-core-application

To simplify my question further. I am trying to use Fluentmigrator on an environment with dotnet runtime only. I cannot use dotnet cli there. Can I use Fluentmigrator.console there? If yes, how?

**Comment by eloekset** [comment]
I'm not much into Docker, but I tried to do an experiment now. I was assuming your issue is about missing SDK tools when building a Docker image from the `microsoft/dotnet:X.X-runtime` image.

I think the answer is that you don't need the dotnet cli to use FluentMigrator. If you take a look at this quickstart guide, you'll see how to include a FluentMigrator runner in your app: https://fluentmigrator.github.io/articles/quickstart.html?tabs=runner-in-process

**Comment by bhavyamathur** [comment]
> I'm not much into Docker, but I tried to do an experiment now. I was assuming your issue is about missing SDK tools when building a Docker image from the `microsoft/dotnet:X.X-runtime` image.
> 
> I think the answer is that you don't need the dotnet cli to use FluentMigrator. If you take a look at this quickstart guide, you'll see how to include a FluentMigrator runner in your app: https://fluentmigrator.github.io/articles/quickstart.html?tabs=runner-in-process

Thanks @eloekset. That's exactly what I am trying. I'm new to both Docker and Fluentmigrator. Is there any way of running these migrations using console in the same environment?

**Comment by eloekset** [comment]
I don't think so, since the console tools depend on the SDK. However, if you build a custom console app and include the runner, you'll be able to run that from the container based on the runtime. This is the docker file that I ended up using for the experiment:
```
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out -f netcoreapp2.2 -r win10-x64

FROM microsoft/dotnet:2.2-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out/ ./
ENTRYPOINT ["ConsoleApp1.exe"]
```

It assumes Windows containers are used. If you use Linux containers, you'll have to modify the runtime parameter of the `dotnet publish` command and the `ENTRYPOINT`.

This is my *ConsoleApp1.csproj* file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.2</TargetFrameworks>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="3.1.3" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.1.3" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="3.1.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.2.0" />
  </ItemGroup>

</Project>
```

The *Program.cs* file is as follows:
```
using System;
using FluentMigrator.Runner;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var serviceProvider = CreateServices();

            // Put the database update into a scope to ensure
            // that all resources will be disposed.
            using (var scope = serviceProvider.CreateScope())
            {
                UpdateDatabase(scope.ServiceProvider);
            }
        }

        /// <summary>
        /// Configure the dependency injection services
        /// </sumamry>
        private static IServiceProvider CreateServices()
        {
            return new ServiceCollection()
                // Add common FluentMigrator services
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    // Add SQLite support to FluentMigrator
                    .AddSQLite()
                    // Set the connection string
                    .WithGlobalConnectionString("Data Source=test.db")
                    // Define the assembly containing the migrations
                    .ScanIn(typeof(_20181228_1252_Initial).Assembly).For.Migrations())
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                // Build the service provider
                .BuildServiceProvider(false);
        }

        /// <summary>
        /// Update the database
        /// </sumamry>
        private static void UpdateDatabase(IServiceProvider serviceProvider)
        {
            // Instantiate the runner
            var runner = serviceProvider.GetRequiredService<IMigrationRunner>();

            // Execute the migrations
            runner.MigrateUp();
        }
    }
}
```


...and the output from the `docker run` command:
![image](https://user-images.githubusercontent.com/791721/50516151-657dba00-0aa9-11e9-9b96-8b8c255c9e9d.png)

**Comment by bhavyamathur** [comment]
Thanks for putting this up @eloekset. I will try your suggestions.

**Comment by bhavyamathur** [comment]
We decided to move on with migrating through code. Thanks @eloekset for your help.
